### ISSUE TITLE
A broken pipeline leaves the last frame on the OBS sink

### ISSUE THREAD

**Issue by crossan007** [fzwoch/obs-gstreamer#1]
a broken GST pipeline causes OBS to continue to display the last received frame on the source.

**Comment by crossan007** [comment]
it seems the only way to recover from this scenario is to either restart OBS, or *edit the text* of the source pipeline declaration.

**Comment by crossan007** [comment]
opening the source pipeline, and clicking "OK" would preferably cause GST to re-try running the pipeline.

**Comment by fzwoch** [comment]
I don't know if there is a way to "clear" frame data from a plugin. I need to check that. Do other plugins behave differently here? I was under the impression OBS tends to keep old data from a plugin unless new data is received.

Restarting may be weird.. if you click "OK" but haven't changed anything OBS doesn't do anything. But it may restart if you click "Cancel"?
