### ISSUE TITLE
Pipelines do not always start

### ISSUE THREAD

**Issue by crossan007** [fzwoch/obs-gstreamer#10]
I have a pipeline source set up that does not start with OBS, but works fine if I manually edit the pipeline after OBS is running.  

I suspect this has to do with the "stop_on_hide" setting, and that there may be some kind of race condition where pipelines having "stop_on_hide" set to false attempt to begin running _before_ OBS is actually ready to map the inputs.   I haven't dug into the code, but from anecdotal usage, this seems to be the case.   Setting "stop_on_hide" to true causes the pipeline to begin correctly at application launch.

```
videotestsrc pattern=18 ! video. alsasrc name=audiosrc device=hw:1 ! audio/x-raw,channels=32,layout=interleaved,rate=48000 ! queue ! deinterleave name=d interleave name=i d.src_0 ! queue ! audioconvert  ! i.sink_0  d.src_1 ! queue ! audioconvert  ! i.sink_1 i. ! audio.

```

I know `stop_on_hide` has been a big point of discussion.  It's worth noting that the other pipelines I'm running "in the background" are configured and started by a python script after a duration of network discovery.  This pipeline running in the background does not have such a startup delay.

**Comment by fzwoch** [comment]
So, do you create this source via script or does it just exist and you are restarting OBS and seen this behavior?
