### ISSUE TITLE
Use openh264enc if x264enc is unavailable (Flatpak gstreamer only has the former) for software encoding

### ISSUE THREAD

**Issue by RushingAlien** [fzwoch/obs-gstreamer#100]
Hello, as the title suggest, the gstreamer plugins that can be found in org.freedesktop.Platform does not include the `x264enc` element, but only the `openh264enc`. I know this is a low priority since this plugin is mainly used with hardware acceleration and flatpak gstreamer has all the vaapi codecs, but i thought i'd let you know.

**Comment by fzwoch** [comment]
OBS comes with its own x264. I don't see any real reason why anyone would go through the extra hoops of installing gstreamer and this plugin just use OpenH264, which is baseline profile only anbd probably also inferior to x264 in any other aspect. That x264 is in this plugin was more to have a comparable test implementation to anything else really.

**Comment by RushingAlien** [comment]
Yeah I am aware about OBS having x264, hence i say this being a low priority, probably not even needed nor necessary. Just thought i'd let you know about it. And thanks, wasn't aware openh264 can only do baseline profile

**Comment by fzwoch** [comment]
It is constrained baseline even. It's most outstanding feature is it's license. It is BSD-2, so commercial entities like to use it because they don't have to touch the GPL.

Closing for now as I don't see anyone ever wanting this in OBS :-)
