### ISSUE TITLE
GStreamer Source: Cannot start pipeline: no property "uri" in element "srtsrc"

### ISSUE THREAD

**Issue by some1chan** [fzwoch/obs-gstreamer#101]
Apologies for my lack of knowledge of GStreamer. The main thing I want working is `srtsrc` but I think this might be all related, so here's just one issue:

When I try to use the following pipeline, I get the following error:
```
# srtsrc uri="srt://placeholder.domain:1234?streamid=play/test" ! decodebin name=bin ! queue ! video. bin. ! queue ! audio.
[obs-gstreamer] GStreamer Source: Cannot start pipeline: no property "uri" in element "srtsrc"
```

The catch here is that if I were to use the terminal instead with the following pipeline, it correctly gets the URI and renders.
```
gst-launch-1.0 -v srtsrc uri="srt://placeholder.domain:1234?streamid=play/test" ! decodebin ! autovideosink
```

This issue only appears in OBS, but not in the terminal. This also happens with the RTMP example, where obs-gstreamer won't work but outside it will.

```
# With the example RTMP pipeline
# uridecodebin uri=rtmp://wowzaec2demo.streamlock.net/vod/mp4:bigbuckbunny_1500.mp4 name=bin ! queue ! video. bin. ! queue ! audio.
[obs-gstreamer] GStreamer Source: Could not determine type of stream.
[obs-gstreamer] GStreamer Source: Internal data stream error.
```

```
# The following command in terminal works for me: 
gst-launch-1.0 -v uridecodebin uri=rtmp://wowzaec2demo.streamlock.net/vod/mp4:bigbuckbunny_1500.mp4 name=bin ! decodebin ! autovideosink
```

Any ideas as to how I'd debug this? Thanks in advance!

**Comment by fzwoch** [comment]
Multiple and/or corrupt GStreamer installations? I have no idea tbh.
