### ISSUE TITLE
No Element "airplaysrc"

### ISSUE THREAD

**Issue by rmathguy** [fzwoch/obs-gstreamer#102]
Hello,

I'm trying to use a separate gstreamer application  in OBS-gstreamer with the given line:
`airplaysrc ! queue ! h264parse ! avdec_h264 max-threads=1 ! videoconvert ! videoscale ! video.`

Which OBS gives an error of:
`error: [obs-gstreamer] ipad: Cannot start pipeline: no element "airplaysrc"`

I do know that the element does exist and is correctly installed as I can run
`gst-launch-1.0 airplaysrc ! queue ! h264parse ! avdec_h264 max-threads=1 ! autovideosink`
and get a window with the correct screen mirroring.

I'm thinking this might be because I'm using the Flatpak version of OBS with the gstreamer plugin also through Flatpak on Arch. But I'm not confident in that being the reason.

**Comment by rmathguy** [comment]
After getting the non-flatpak version of OBS and obs-gstreamer up and running. Now the airplaysrc source working, I'm pretty sure it was a flatpak issue.

**Comment by fzwoch** [comment]
Sure. Flatpak runs in a container isolated from your real system. So it comes with its own set of GStreamer libraries when you install the plugin. Therefore you will not have any custom elements you have installed on your system, but only the ones that come with the Flatpak runtime dependencies.
