### ISSUE TITLE
nixos with gstreamer not working

### ISSUE THREAD

**Issue by kesu33** [fzwoch/obs-gstreamer#105]
rtspsrc location=rtsp://*****:****@192.168.0.64:554/Streaming/Channels/101 latency=0 buffer-mode=auto ! rtph265depay ! avdec_h265 ! video.

error: [obs-gstreamer] GStreamer Source: Cannot start pipeline: no element "rtspsrc"

**Comment by fzwoch** [comment]
I have no idea about nixos, but you will need to install the plugins on that platform you want to use.

**Comment by kesu33** [comment]
It is already working well when directly open using gstreamer..
