### ISSUE TITLE
gstreamer plugin is not available in OBS ver29.1.3

### ISSUE THREAD

**Issue by tsuna6** [fzwoch/obs-gstreamer#106]
Hi there, I just follow every single manual (like copy the gstreamer plugin OBS and paste it in OBS plugin 64 folder) and also i have installed gstreamer gstreamer-1.0-mingw-x86_64-1.22.5.msi but still no available when i open the OBS ver.29.1.3

Please help me about this. Thanks

**Comment by fzwoch** [comment]
Check https://github.com/fzwoch/obs-gstreamer/issues/25#issuecomment-662004613

**Comment by tsuna6** [comment]
Thankyou. Very helpful
