### ISSUE TITLE
Effect filter

### ISSUE THREAD

**Issue by devyx** [fzwoch/obs-gstreamer#108]
Enhancement request. 

Current implemenation does not allow to use the gstreamer-filter on a lot of sources as only Effect filter is selectable in the UI. Is there a plan to add this functionality? 

My use case is a subset of this functionality - I would like to pipe a specific source to a gst pipeline to output it over the network.

**Comment by fzwoch** [comment]
Not planned. It is unclear from the docs on how to copy the GPU texture back to host memory.

**Comment by devyx** [comment]
I guess there is a way as a obs-ndi filter does exactly that - https://github.com/obs-ndi/obs-ndi/blob/master/src/obs-ndi-filter.cpp#L151 
Thank you for the information.

**Comment by fzwoch** [comment]
Of course there is a way, but I won´t spend a week dissecting this.

**Comment by fzwoch** [comment]
Not sure if it works, but perhaps you can use https://obsproject.com/forum/resources/source-clone.1632/for your use case.
