### ISSUE TITLE
Where can I take C libraries?

### ISSUE THREAD

**Issue by marataziat** [fzwoch/obs-gstreamer#11]
You didn't give any instructions, how to install libraries for obs and gstreamer and where can I download it?

**Comment by fzwoch** [comment]
That depends on the target platform. And even then there are often several possibilities. Especially Linux and Windows differ significantly here.

GStreamer offers prebuild binaries for Windows and macOS. They can be a good start. The OBS library should come with OBS (I would assume) - I actually build mine myself. This really depends on a lot which toolchains you want to use. If you give some more details what exactly you aim for I can give some more hints.

**Comment by marataziat** [comment]
I'm using ubuntu

**Comment by fzwoch** [comment]
For installing GStreamer then:
```
sudo apt install libgstreamer1.0-dev
```

For OBS I'm a bit unsure as my copy was build from source. I think there is some installer provided by OBS? Ideally it also install the required `libobs.so`.

Maybe you need to run:
```
sudo ldconfig
```
To make the system locate and find the `libobs.so` once.

If you follow the build instructions in the `README.md` it _should_ work. But report back if not.

**Comment by marataziat** [comment]
How to fix it?
> meson.build:24:27: ERROR: Unknown method "has_link_argument" in object.
