### ISSUE TITLE
Error with a few different streams

### ISSUE THREAD

**Issue by privatesam** [fzwoch/obs-gstreamer#111]
Running Linux Portable OBS  30.0.2 with the gstreamer plugin already packaged [https://github.com/wimpysworld/obs-studio-portable](url).  The test card thingy works fine.  I'm trying to pipe in various different streams but none are working.  One is a HLS stream from a provider who provides the links either as *.m3u8 or *.ts but neither work.  The commands and errors below:

`uridecodebin uri=http://xyv.xyz:8080/live/xyz/xyz/4455.ts name=bin ! queue ! video. bin. ! queue ! audio.`

errors with:

`09:44:25.393: [obs-gstreamer] GStreamer Source: No decoder available for type 'video/mpegts, systemstream=(boolean)true, packetsize=(int)188'.
09:44:25.394: [obs-gstreamer] GStreamer Source: Your GStreamer installation is missing a plug-in.
09:44:25.411: [obs-gstreamer] GStreamer Source: Internal data stream error.
`

and the command:

`uridecodebin uri=http://xyv.xyz:8080/live/xyz/xyz/4455.m3u8 name=bin ! queue ! video. bin. ! queue ! audio.`

errors with:

`09:44:25.411: [obs-gstreamer] GStreamer Source: Internal data stream error.
09:45:44.611: [obs-gstreamer] GStreamer Source: No decoder available for type 'application/x-hls'.
09:45:44.611: [obs-gstreamer] GStreamer Source: Your GStreamer installation is missing a plug-in.`

Not sure if its something I'm doing wrong or whether my provider is doing something funky with the streams or whether I need to add something.  Any help appreciate.  Thanks for this plugin!

**Comment by privatesam** [comment]
Sorry I never replied to say that I didn't have gstreamer installed on the actual OS so the plugin was struggling.  Should've let you know.  Thanks.

**Comment by fzwoch** [comment]
Thanks.

> The test card thingy works fine.

This sounded like the default pipeline with the test pattern was working, so I assumed it was at least partially installed. But perhaps I misunderstood.
