### ISSUE TITLE
GStreamer Encoders not showing up on OBS 30.2

### ISSUE THREAD

**Issue by Faugus** [fzwoch/obs-gstreamer#113]
I'm on Arch Linux.
I tried installing it manually and also the AUR package.

Also tried on Fedora. No luck.

![image](https://github.com/user-attachments/assets/70f38677-e4e0-4384-ad0c-264c281511ee)

![image](https://github.com/user-attachments/assets/f86a08e8-62ad-4a6f-95c4-5f1a2640675d)

**Comment by fzwoch** [comment]
They have been marked deprecated here:
https://github.com/fzwoch/obs-gstreamer/commit/e347bc0e975221d9630a0a71b27888ca1ccba941

If you are looking for the VAAPI encoders you should look here:
https://github.com/fzwoch/obs-vaapi
