### ISSUE TITLE
obs wont load gstream plugin

### ISSUE THREAD

**Issue by Mrtach** [fzwoch/obs-gstreamer#114]
I tried everything was mention in the obs thread and here but obs still won't load the plugin
```

LoadLibrary failed for '../../obs-plugins/64bit/obs-gstreamer.dll': (null) (126)
Module '../../obs-plugins/64bit/obs-gstreamer.dll' not loaded
```

> Windows Version: 10.0 Build 19045 (release: 22H2; revision: 4894; 64-bit)
> Running as administrator: false
> Windows 10/11 Gaming Features:
> Game Bar: Off
> Game DVR: Off
> Game DVR Background Recording: Off
> Browser Hardware Acceleration: true
> Qt Version: 6.6.3 (runtime), 6.6.3 (compiled)
> Portable mode: false
> OBS 30.2.3 (64-bit, windows)

I've installed all c++ redistributables, gstream minigw at c:/
I set the path to minigw root folder and bin folder
I tried older versions of gstream-plugin, all the same error

**Comment by fzwoch** [comment]
Can't help much here. I suspect you somehow made a mistake setting it up.
C++ redists should not be needed as the pre-compiled is mingw. (and everything is C anyway)

Perhaps https://github.com/lucasg/Dependencies can give you more insights what may not be found.

**Comment by jahaddow** [comment]
Same issue. OBS 30.2.3. Windows 11
