### ISSUE TITLE
OBS gstreamer consistent jitter 

### ISSUE THREAD

**Issue by danielamar101** [fzwoch/obs-gstreamer#115]
I have the following pipeline in OBS gstreamer:

```
rtmpsrc location=<rtmp server> ! queue max-size-time=1000000000 max-size-bytes=10485760 max-size-buffers=1000 ! decodebin name=bin
bin. ! queue max-size-time=1000000000 ! videoconvert ! video/x-raw ! video.sink
bin. ! queue max-size-time=1000000000 ! audioconvert ! audio/x-raw ! audio.sink
```
After checking the recording I hear and see alot of jitter. The output is unusable as its that bad.

However, running the same pipeline in a terminal:
```
gst-launch-1.0 rtmpsrc location=<rtmp server> \
    ! queue max-size-time=1000000000 max-size-bytes=10485760 max-size-buffers=1000 \
    ! decodebin name=bin \
    bin. ! queue max-size-time=1000000000 \
         ! videoconvert \
         ! video/x-raw \
         ! autovideosink \
    bin. ! queue max-size-time=1000000000 \
         ! audioconvert \
         ! audio/x-raw \
         ! autoaudiosink
```

It is working perfectly fine with absolutely no jitter.

I am on an M1 Macbook pro. What could be the reason for this issue?

**Comment by fzwoch** [comment]
Perhaps some of the settings in the plugin? What timestamps/sync to use etc.. hard to tell from the outside I'm afraid.

**Comment by danielamar101** [comment]
It was actually a problem with timestamp syncing. Simply checking the right boxes in the pipeline menu in OBS managed to fix the problem
