### ISSUE TITLE
obs doesn't see plugin

### ISSUE THREAD

**Issue by gothmog123** [fzwoch/obs-gstreamer#117]
Hello I've installed the plugin from the Arch AUR, following the archwiki article but the obs is not picking up on the plugin.

There is no option to select a gstreamer output in the output options..... 

Help?

**Comment by fzwoch** [comment]
Output is not found in any UI. It is more for application developers that build around libobs themselves.

**Comment by gothmog123** [comment]
i see thanks

**Comment by fzwoch** [comment]
What were you trying to use from it anyway?

You _can_ trick OBS by manually editing its config.

**Comment by gothmog123** [comment]
sorry i understand what happened now. the arch wiki links to obs-gstreamer instead of obs-vaapi which is wrong. it should link to obs-vaapi, which is the package that gives you gstreamer output in obs

**Comment by fzwoch** [comment]
Ah, it is not technically an output. That is different.

You were looking for the encoders! Indeed they have been hid here in the latest version in favor for the obs-vaapi one. That wiki should probably be updated.

**Comment by gothmog123** [comment]
yeah it should
