### ISSUE TITLE
Precompiled Windows DLL

### ISSUE THREAD

**Issue by crossan007** [fzwoch/obs-gstreamer#13]
I can't seem to get OBS to load the gstreamer Windows DLL, but I'm probably doing something wrong

Running OBS  OBS 22.0.2 (64-bit, windows)
I installed both gstreamer-1.0-devel-x86_64-1.15.1.msi and gstreamer-1.0-x86_64-1.15.1.msi from https://gstreamer.freedesktop.org/data/pkg/windows/1.15.1/

Logs indicate failure to locate the dll:
```
21:13:01.034: LoadLibrary failed for '../../obs-plugins/64bit/gstreamer.dll': The specified module could not be found.
21:13:01.034:  (126)
21:13:01.034: Module '../../obs-plugins/64bit/gstreamer.dll' not loaded
````

Any pointers would be appreciated.

**Comment by crossan007** [comment]
[2019-01-31 21-12-58.txt](https://github.com/fzwoch/obs-gstreamer/files/2819796/2019-01-31.21-12-58.txt)

**Comment by crossan007** [comment]
I'm trying again with the 1.14.4 version of GStreamer runtime (since that's what's linked in the CI step):
https://github.com/fzwoch/obs-gstreamer/blob/master/.gitlab-ci.yml#L72

**Comment by crossan007** [comment]
Not sure if all of these steps were necessary,  but I had to:

Install GST 1.14.1
Copy binaries and dlls to both `C:\Program Files (x86)\obs-studio\bin\64bit` and `C:\Program Files (x86)\obs-studio\obs-plugins\64bit` (Probably not necessary, and certainly a mess)

Configure environment variable GST_PLUGIN_PATH = `D:\gstreamer\1.0\x86_64\lib\gstreamer-1.0`  - this was necessary to fix log entries of `Cannot start GStreamer: no element "videoconvert"`

**Comment by fzwoch** [comment]
Thanks for the feedback.

Ideally you only have to install the run-time package of GStreamer. The devel package should not be needed. For the GStreamer DLLs to be found it may be required to add the GStreamer `bin` folder (or wherever the DLLS are located) to the system's PATH variable. I can't remember if the installer already does that. Then GStreamer should also know where to find its plugins.

Dependency Walker (http://dependencywalker.com/) is a good tool to verify if all dependency DLLs could be found (It reports some erros about windows own stuff which can be ignored). If all GStreamer and OBS related DLLs are not repoted it should be ready to go.

I also think it should work with other GStreamer versions as well as long as the API's being used don't change. The things being used should be stable through all the 1.x releases - but i can't remember for sure..

**Comment by crossan007** [comment]
I did a clean install of Windows and OBS, and I can confirm that installing gstreamer 1.15.1 release, adding the  gstreamer bin folder to the system path, and placing the obs-gstreamer.dll plug-in in the obs plugins folder is sufficient for proper functionality.

**Comment by bradisbell** [comment]
Could you please elaborate on what the plugin is using, specifically?

I've ensured that the environment path does contain my gstreamer bin directory.  I've also tried copying all of gstreamer's bin to the OBS plugins directory.  I'm getting the same error previously mentioned on this thread, so I must be missing something somewhere.

**Comment by fzwoch** [comment]
It basically is just using the GStreamer runtime (well and OBS library of course). So it will probably use something like

- libgstreamer-1.0.dll
- libgstreamer-video-1.0.dll
- libgstreamer-audio-1.0.dll
- libgstreamer-app-1.0.dll

Of course when the plugin gets loaded the GStreamer runtime will load other libraries and plugins by its own.

Usually they should get found by the plugin if the directory where these are found is in the system path. I think this is something like `C:\gstreamer\1.0\x86_64\bin` or similar. And I think you can check this by just trying to run `gst-inspect-1.0` from ANY OTHER directory than where it is located which is in the same directory as the .dll files I think.

Make sure all components are 64-bit versions (OBS Studio and GStreamer) since the pre-build plugin is for 64-bit only. See `dependency walker` above if you want to track down potential dependency issues.

**Comment by random-facades** [comment]
FYI: 1.18 No longer has the same names.

Based on [Dependencies v1.10](https://github.com/lucasg/Dependencies/)
libglib-2.0-0.dll -> glib-2.0-0.dll
libgobject-2.0-0.dll -> gobject-2.0-0.dll
libgstapp-1.0-0.dll -> gstapp-1.0-0.dll
libgstaudio-1.0-0.dll -> gstaudio-1.0-0.dll
libgstreamer-1.0-0.dll -> gstreamer-1.0-0.dll
libgstvideo-1.0-0.dll -> gstvideo-1.0-0.dll

**Comment by fzwoch** [comment]
This pretty much depends on which version of the gstreamer SDK you install. Files with lib prefix are from the mingw version while the others are from msvc. My stuff is tested with mingw only. It may work with msvc ones too, but you have to figure out differences yourself.
