### ISSUE TITLE
Sources on Windows Don't map audio

### ISSUE THREAD

**Issue by crossan007** [fzwoch/obs-gstreamer#14]
GStreamer sources on Windows don't seem to connect the audio to the output stream.

I can see the audio sources from my Gstreamer pipelines rendered in the mixer; however, the audio does not actually get output to the stream / recording.   If I choose to monitor one of the sources, it will be "picked up" by the OBS capture of  my default audio device; but not directly from obs-gstreamer:

![image](https://user-images.githubusercontent.com/11679900/52157499-5caa7600-265d-11e9-90ee-7a35de9d0136.png)

**Comment by fzwoch** [comment]
Not sure if I understood. I mean if the OBS mixer is displaying activity we are successfully sending audio into OBS. Whether it gets rendered by the mixer or output by the speaker solely depends on the settings of the OBS mixer I believe. I never came across anything that the plugin can use to have any effect on this. Also the Window's plugin code should not differ from any other platform. How many ausio channels are fed by the Gstreamer plugin?

**Comment by fzwoch** [comment]
Let me know if this is still a thing and you have some more info on that. I will close this in the meantime.

**Comment by ancer** [comment]
I have the same issue with audio source. I tried filesrc, rtmpsrc, autoaudiosrc sources and all of them are not recored to output file.

If I enable monitoring, sound is recorded but is extremely distorted (filesrc and rtmpsrc). I hear it distorted and it is recorded distorted.

The only working option is to use directsoundsink as gstreamer audio sink - it works like monitoring option (however without volume control) and the sound is not distorted and is recorded fine.

Maybe it is just Windows platform specific problem and on Mac audio works perfectly well. But I need Windows :(

**Comment by fzwoch** [comment]
Do you have some example media / media URL and pipeline string for testing?

**Comment by fzwoch** [comment]
So the default pipeline for me worked as expected. The test sounds was recorded to file just fine. Running on Windows 10 / Virtual-box. So if there is something odd I would need some steps how to reproduce the issue.

**Comment by fzwoch** [comment]
No feedack..
