### ISSUE TITLE
Watching a M3U8 stream that uses small TS files

### ISSUE THREAD

**Issue by robinkooli** [fzwoch/obs-gstreamer#15]
I can't get it working, tried lot of different configurations.

M3U8 file looks like this:
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:893
#EXT-X-TARGETDURATION:4
#EXTINF:3.334,
40WjFnamJgYWdrTjZ7MTA2Ojw4NDc3-001550180296886_000000000000000_L42WQ3TCMJUGE3KEHA_1080p_d0_NZXWIZLTMM_r626853397090207077.ts?extra=
#EXTINF:3.325,
40WjFnamJgYWdrTjZ7MTA2Ojw4NDc3-001550180300249_000000000000000_L42WQ3TCMJUGE3KEHA_1080p_d0_NZXWIZLTMM_r2079583977462108025.ts?extra=
#EXTINF:3.317,
40WjFnamJgYWdrTjZ7MTA2Ojw4NDc3-001550180303572_000000000000000_L42WQ3TCMJUGE3KEHA_1080p_d0_NZXWIZLTMM_r6522384740513319295.ts?extra=
#EXTINF:3.329,
40WjFnamJgYWdrTjZ7MTA2Ojw4NDc3-001550180306910_000000000000000_L42WQ3TCMJUGE3KEHA_1080p_d0_NZXWIZLTMM_r5131058999397848931.ts?extra=`

Used this cheat sheet for help: https://github.com/xmementoit/gstreamerCheatsheet/blob/master/README.md#play-hls-http-live-streaming-url-using-gstreamer-pipeline

**Comment by crossan007** [comment]
Does the gstreamer test video src work for you?

That will at least tell us if obs-gstreamer is installed properly and "talking to" obs.

Also, what os are you on? What version of gstreamer, and what version of obs?

**Comment by robinkooli** [comment]
Running latest Windows 10 with latest gstreamer (32bit and 64bit) installed, the test works.

**Comment by fzwoch** [comment]
Not sure which pipeline and streams you have tried. But I have tested and added an HLS example to the README.md:

```
uridecodebin uri=http://184.72.239.149:1935/vod/mp4:sample.mp4/playlist.m3u8 name=bin ! queue ! video. bin. ! queue ! audio.
```

This did work just fine for me.

**Comment by robinkooli** [comment]
Doesn't seem to work with streams from VKontakte (VK).
Recently VK streams also stopped working on VLC Player, but is fixed on it's settings by changing MPEG-TS demuxer setting to not trust in-stream PCR and to seek based on percent not time.

VLC has following error without the fix:
`ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1)`

**Comment by fzwoch** [comment]
I assume these streams are not public accessible for testing?

So if they offer invalid streams do they do this on purpose? Anyway if they cannot be played with the `gst-play-1.0` application there is nothing this plugin can do to fix this. Perhaps there are some specific GStreamer options on some of the elements in question like the workarounds in VLC - but I'm not sure. If the expectation is that GStreamer can play these streams I suggest to discuss these upstream to the GStreamer people as they are ones who may be able to fix it.

**Comment by robinkooli** [comment]
You can find VK streams here: https://vk.com/video
Opening a stream, right clicking it and copying the debug info gets you the Live HLS M3U8 file.

**Comment by fzwoch** [comment]
Yes, so it throws several errors. Its either multiple programs in these streams or broken in a way the parser completely freaks out. Most likely on purpose to get people using their site instead of grabbing streams by 3rd parties. IT's probably a cat and mouse game to keep up with whatever they are doing to their streams. Either way - if it supposed to get fixed it must be done by the GStreamer project. Nothing this plugin can do here, so I'm closing this.
