### ISSUE TITLE
Can't build on Ubuntu 18.04LTS - Meson Version Error

### ISSUE THREAD

**Issue by 79rpm** [fzwoch/obs-gstreamer#16]
I am on Ubuntu 18.04LTS, the result of the compilation with meson is the following:

meson --buildtype=release build
The Meson build system
Version: 0.45.1
Source dir: /home/macnica/Documents/OBS/obs_gstreamer/obs-gstreamer
Build dir: /home/macnica/Documents/OBS/obs_gstreamer/obs-gstreamer/build
Build type: native build

meson.build:21:0: ERROR: Meson version is 0.45.1 but project requires >=0.46.

A full log can be found at /home/macnica/Documents/OBS/obs_gstreamer/obs-gstreamer/build/meson-logs/meson-log.txt

Do I need to rebuild a newer version of meson for Ubuntu 18.04?

**Comment by fzwoch** [comment]
I'm afraid so. But it should be quite easy. The recommended way is to install `meson` via the python package manager an not via the Ubuntu's `apt`.

E.g.
```
sudo apt install python3-pip
pip3 install meson
```

**Comment by 79rpm** [comment]
Thank you for the quick reply. I will do so!

**Comment by infinit-loop** [comment]
I have installed through "pip3 install --user meson" but it is not working .
It is again saying update meson. What should I do.

**Comment by fzwoch** [comment]
So what do the versions say? meson currently is at `0.54.1`. If you have an old version installed you may need to add `--upgrade` to the pip command.

**Comment by infinit-loop** [comment]
Thanks for the reply actually problem solved, actually error was that "install meson , meson not found" but I have already installed it through pip.

**Comment by rokibhasansagar** [comment]
## How to Use latest meson?
First, remove meson installed by apt if installed.
`sudo apt purge meson -y`

Then install via pip3
`sudo pip3 install meson`

Then make a symlink in bin folder from local bin
`sudo ln -s /usr/local/bin/meson /usr/bin/meson`

Now check `which meson && meson --version`

**Comment by Shadowblitz16** [comment]
pip3 doesn't exist

**Comment by panpan2** [comment]
@Shadowblitz16 install it
```
sudo apt install python3-pip
```

**Comment by DonLarry** [comment]
I got this error while running the meson command (`meson _build --prefix=/usr`)

```
Run-time dependency libpipewire-0.3 found: NO (tried pkgconfig and cmake)

src/meson.build:108:0: ERROR: Dependency "libpipewire-0.3" not found, tried pkgconfig and cmake
```

I have ubuntu 20.04.3 LTS, and I just have `libpipewire-0.2`, but not `libpipewire-0.3`. Should I add the ubuntu 20.10 repository to install `libpipewire-0.3`? or there is other solution for my ubuntu version? (I just want to avoid conflicts because of my packages and my ubuntu version)

**Comment by fzwoch** [comment]
This plugin does not require `pipewire`. So I'm not sure where this error is coming from.

**Comment by DonLarry** [comment]
oh... I was just following the [Download](https://github.com/wwmm/easyeffects/wiki/Installation-from-Source#download) and [Build & Install](https://github.com/wwmm/easyeffects/wiki/Installation-from-Source#build--install) steps because I tried to do the normal installation for [ubuntu](https://github.com/wwmm/easyeffects/wiki/Installation-from-Source#debian--ubuntu) but I got an error while trying to execute this command `debuild -i.* -us -uc`

**Comment by DonLarry** [comment]
I'm on a zsh shell and running `debuild -i.* -us -uc`, I got `zsh: no matches found: -i.*`.
Then if I run `debuild "-i.*" -us -uc`, I got this:
```
 dpkg-buildpackage -us -uc -ui -i.*
dpkg-buildpackage: info: source package pulseeffects
dpkg-buildpackage: info: source version 4.8.2-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Mikhail Novosyolov <mikhailnov@dumalogiya.ru>
 dpkg-source -i.* --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-source: error: source package has two conflicting values - easyeffects and pulseeffects
dpkg-buildpackage: error: dpkg-source -i.* --before-build . subprocess returned exit status 25
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i.* failed
```
That's why I tried with the section "Download" and "Build & Install" (which I thought it is like a general installation method?, idk)

**Comment by fzwoch** [comment]
The TL;DR install method is outlined in the `README.md` of this project. The others things have nothing to do with this plugin.

**Comment by myunghunkang** [comment]
In Ubuntu 18.04, I've got latest version of meson.

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt list | grep python3.8
sudo apt-get install python3.8
/usr/bin/python3.8 -m pip install --user meson

**Comment by Abdull** [comment]
```
pipx install meson
```
