### ISSUE TITLE
obs-gstreamer plugin not found in source list - Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by 79rpm** [fzwoch/obs-gstreamer#17]
Hello,

The newly built plugin does not show up in OBS. The *.so file is stored in a folder that is not checked by OBS at boot. When I click + under source in OBS GStreamer is not listed.

This is the last step in the obs-plugin installation note:

~/Documents/OBS/obs_gstreamer/obs-gstreamer$ sudo ninja -C build install
ninja: Entering directory `build'
[0/1] Regenerating build files.
The Meson build system
Version: 0.50.0
Source dir: /home/macnica/Documents/OBS/obs_gstreamer/obs-gstreamer
Build dir: /home/macnica/Documents/OBS/obs_gstreamer/obs-gstreamer/build
Build type: native build
Project name: obs-gstreamer-source
Project version: undefined
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-16ubuntu3) 7.3.0")
Build machine cpu family: x86
Build machine cpu: i686
Compiler for C supports link arguments -static-libgcc: YES
Library obs found: YES
Dependency gstreamer-1.0 found: YES (cached)
Dependency gstreamer-video-1.0 found: YES (cached)
Dependency gstreamer-audio-1.0 found: YES (cached)
Dependency gstreamer-app-1.0 found: YES (cached)
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja
[0/1] Installing files.
Installing gstreamer.so to /usr/local/lib/obs-plugins

To fix this problem I did: sudo cp /usr/local/lib/obs-plugins/gstreamer.so /usr/lib/obs-plugins/
OBS looks (at least with Ubuntu) under /usr/lib/obs-plugins to find any *.so files.

**Comment by fzwoch** [comment]
Yes, this depends on how you have installed OBS. I think there are at least three methods:

- Install from Ubuntu package manager.
- Install from OBS official PPA.
- Build and install OBS from source yourself.

I think each one of them installs in a different directory and also has a different plugin directory to that they can be installed in parallel.

The default install ob the plugin assumes you have build and installed OBS yourself (that's what I did, and that's the only reason why it does it that way).

Glad you got it sorted though :-)

**Comment by 79rpm** [comment]
Thanks Florian
