### ISSUE TITLE
Gstreamer input and encoder not visible under OBS 24.0.0, Ubuntu 19.04

### ISSUE THREAD

**Issue by matiaspl** [fzwoch/obs-gstreamer#19]
The plugin never shows up in log files nor is visible as a source or encoder.
I tried both building from source and using the supplied binary and moving the plugin between folders (I use PPA OBS, all my other plugins placed in /usr/share/obs/obs-plugins and ~userdir/.config/obs-studio/plugins work fine).
Ubuntu 19.04, OBS 24.0.0

**Comment by crossan007** [comment]
Does #17 address what you're seeing?

**Comment by crossan007** [comment]
When you compiled the plugin, did you receive any warnings about missing `gstreamer` dependencies? (https://github.com/fzwoch/obs-gstreamer/issues/11#issuecomment-421354452)

**Comment by matiaspl** [comment]
I checked both before opening new issue. Building raises a single warning:

> $ ninja -C build
ninja: Entering directory `build'
[2/4] Compiling C object 'obs-gstreamer@sha/gstreamer-encoder.c.o'.
../gstreamer-encoder.c: In function ‘gstreamer_encoder_create’:
../gstreamer-encoder.c:69:3: warning: format not a string literal and no format arguments [-Wformat-security]
   blog(LOG_ERROR, err->message);
   ^~~~
[4/4] Linking target obs-gstreamer.so.

**Comment by fzwoch** [comment]
You are on dev branch? The build looks fine.  Are you at head of dev? There was some wonky bit that prevented loading due to missing symbols. Latest should load at least. If not maybe check logs or exported symbols for hints. Dev is still dev after all.

**Comment by matiaspl** [comment]
Ok, it seems I didn't get enough sleep back then. Your plugin works fine if placed in the ACTUAL plugins folder which for the PPA OBS is /usr/lib/obs-plugins and *not* /usr/share/obs/obs-plugins. NB it doens't seem to load from the userdir folder.
Thanks for all your great work!
