### ISSUE TITLE
Memory Leak in Gstreamer-encoder

### ISSUE THREAD

**Issue by pgwipeout** [fzwoch/obs-gstreamer#22]
While running the gstreamer-encoder function, memory usage of OBS slowly increases until oom murders it.
This does not appear to affect the gstreamer-source function, only the encoder function.

Upon stopping the gstreamer-encoder, memory usage stabilizes, but does not return to normal without closing obs.
I've run the same string with gst-launch and videotestsrc and memory usage is stable, showing the issue is likely in appsrc or appsink.
Memory usage increase is proportional to the data rate, larger resolution or higher bitrates affect the rate of increase.

OBS reports 0 memory leaks upon closing out.

**Comment by fzwoch** [comment]
Thanks for testing and reporting. I believe the above change should address your issue. I did a quick test and it seemed to improve the behavior.

It was a wrong assumption who is responsible to release the encoded bit stream data. Hopefully that didn't introduce any other side effects..

**Comment by pgwipeout** [comment]
Thanks!

Short term it appears to have resolved the leak, I'll run a few hours to be sure though before closing the issue.
