### ISSUE TITLE
Source doesn't auto-start when not in view

### ISSUE THREAD

**Issue by ethaniel** [fzwoch/obs-gstreamer#26]
Thank you for an amazing module!

I have several scenes (all of which have gstreamer sources through your plugin). I've noticed that they start receiving and playing data only when I open each scene manually for the first time. This is different from the expected behaviour that all sources should start playing when OBS starts.

I have "stop pipeline when hidden" disabled.

How can I get them to play when OBS starts (even when the scene is hidden from view)?

**Comment by fzwoch** [comment]
I think currently it can't to that. Probably because the OBS documentation is not clear enough when to start/stop things.

If you can build the plugin yourself perhaps you have some luck with this patch:

```diff

diff --git a/gstreamer-source.c b/gstreamer-source.c
index f9a49ef..6da6723 100644
--- a/gstreamer-source.c
+++ b/gstreamer-source.c
@@ -340,6 +340,9 @@ void *gstreamer_source_create(obs_data_t *settings, obs_source_t *source)
        data->source = source;
        data->settings = settings;
 
+       if (obs_data_get_bool(settings, "stop_on_hide") == false)
+               start(data);
+
        return data;
 }
 
```

Let me know if that works..

**Comment by ethaniel** [comment]
Yup, it works!!! Woohoo, thank you so much!!!
