### ISSUE TITLE
Example: RaspberryPi Zero --[wifi]--> OBS

### ISSUE THREAD

**Issue by crossan007** [fzwoch/obs-gstreamer#3]
Not exactly an "issue," but an example.

On Raspberry Pi Zero:
```
gst-launch-1.0 rpicamsrc name=videosrc keyframe-interval=10 shutter-speed=0 iso=200 drc=0 exposure-mode=1 metering-mode=1 awb_mode=6 bitrate=0 quantisation-parameter=22 do-timestamp=true ! h264parse ! video/x-h264,framerate=30/1,width=1280,height=720 ! matroskamux ! queue ! tcpserversink host=0.0.0.0 port=8675
```

On OBS:
```
tcpclientsrc host=PiZero port=8675 ! queue ! matroskademux ! decodebin ! videoconvert ! videorate ! videoscale ! video/x-raw, framerate=30/1, width=1920, height=1080 ! video.
```
![image](https://user-images.githubusercontent.com/11679900/42482323-fc9258c8-83b4-11e8-8fe2-093c33836e1d.png)

**Comment by fzwoch** [comment]
Looks good to me :-)

One note: is there a reason to use Matroska muxing for streaming over IP? Maybe using `gdppay` and `gdpdepay` encapsulating the H.264 data is the weapon of choice for such use cases. But I guess as long as it works..

And another: `videoscale` on the GStreamer side is done in software and may be slow. Perhaps just consider receiving the unscaled image and scale the canvas on the OBS scene. Then it will be scaled at the GPU layer of OBS.

**Comment by crossan007** [comment]
So, before obs, I was hacking on "voctomix". They have a Python ui which manipulates gstreamer pipelines to provide a video mixer.   

Their transport of choice was always matroska - something about how it preservers timestamps differently/better.


Looking at docs for gdppay, it may do the job just as well.

**Comment by crossan007** [comment]
Good catch with the video scale

**Comment by crossan007** [comment]
Hey, do you think we could (or should) pass h264 directly into OBS?

**Comment by crossan007** [comment]
interesting.  I just tried both `matroskamux` / `matroskademux` and `gdppay` / `gdpdepay`, and `gdp`* doesn't seem to work at all, while matroska seems to work like a charm.

Now I'm curious.

**Comment by Dregu** [comment]
Been fiddling with raspi streaming quite a lot, and all the muxing and converting just seems useless if you have a good network. I also posted this on the forums, but
```
raspivid -n -t 0 -w 1280 -h 720 -g 60 -fps 30 -b 2500000 -mm average -ex fixedfps -ih -pf high -o udp://10.0.0.176:5000

udpsrc port=5000 ! h264parse ! avdec_h264 ! video.
```
works just fine over my wifi.

**Comment by crossan007** [comment]
@Dregu  I think you bring up a valid point here - "good network"

I'm noticing that my PiZero reports a great wifi connection _until_ I start streaming video - then it drops to 5.5 mbps.

Additionally, I'm noticing some weird sync issues (I believe unrelated to network, but rather ISO).

If I request above a certain ISO, then the resultant H264 frames are late (compared to frames being generated by a separate camera, on a separate pi on a separate network connection.)

below ISO 400, then the H264 frames from the zero are only about 100 ms behind frames from a Logitec C920; however if i request ISO600 from the Pi camera, then the frames are a few seconds late.   Again - this could be a network issue (as higher ISO = more video data in a dim lit area = more network throughput).

sorry for the ramble - it's late and I'm wrapping up for the evening.

I think I've posted about this on a different GH issue: https://github.com/thaytan/gst-rpicamsrc/issues/71

**Comment by crossan007** [comment]
I'm planning on porting https://github.com/crossan007/PiCamFleetMapper into an OBS plugin with a UI for managing "remote cameras" within OBS.

**Comment by crossan007** [comment]
Another example:

Allen and Heath QU32 Mixing console USB out -> GStreamer/OBS.  Select the first 2 of the 32 channels on the source, and trim to stereo

```
videotestsrc pattern=18 ! video. alsasrc name=audiosrc device=hw:1 ! audio/x-raw,channels=32,layout=interleaved,rate=48000 ! queue ! deinterleave name=d interleave name=i d.src_0 ! queue ! audioconvert  ! i.sink_0  d.src_1 ! queue ! audioconvert  ! i.sink_1 i. ! audio.
```

**Comment by crossan007** [comment]
Closing this, as it's not actually an issue.

**Comment by crossan007** [comment]
@fzwoch would you consider opening the wiki on this repo?   I'd gladly contribute some documentation and  examples.

**Comment by fzwoch** [comment]
I guess I should. These examples are great so I left this issue open. I just never did before so I need to check what to do so people can contribute to. Hopefully I can check this in the next couple of days.

**Comment by fzwoch** [comment]
I have set the option for the wiki to be world writable I think. If it works you can start adding some stuff there as you like. I'm a bad documentation person myself..

**Comment by hotsparklab** [comment]
After a weekend and week evenings of banging my head against a wall, trying to get low-latency video from a Pi to OBS, this issue made my month! Here's a resulting quick project that attempts to break it down for more experience levels and alleviate the pain next time I do this (memory not the best). Thanks for this project and post @fzwoch, @Dregu and @crossan007!

https://github.com/hotsparklab/raspivid-udp-camera

I put a note of special thanks in there referencing this "issue". Thanks for being awesome! :D
