### ISSUE TITLE
Release of latest changes

### ISSUE THREAD

**Issue by sapkra** [fzwoch/obs-gstreamer#35]
I have seen that the last version is almost a year old, although the repository is well maintained.
Would it be possible to release the latest changes?

btw. the latest release is not working with the latest OBS Studio on macOS - I had to build it myself

**Comment by fzwoch** [comment]
Yeah, well I need some time and the right mood to do so :-)

But in the meantime - you can always grab the latest change from the Gitlab CI: https://gitlab.com/fzwoch/obs-gstreamer

**Comment by fzwoch** [comment]
Depending on when the last release was made - I believe OBS v25 did do an breaking API change for plugins so they had to be recompiled. And then again - compiled with v25 do not work with v24 and vice versa.. Not sure if v26 will do the same.. so I guess I will hold of a bit longer doing a release.

**Comment by fzwoch** [comment]
Done with 0.2.0.
