### ISSUE TITLE
Plugin not working on OBS 25

### ISSUE THREAD

**Issue by AvrumFeldman** [fzwoch/obs-gstreamer#37]
Downloaded the latest build from gitlab CI/CD but the plugin does not show up in OBS studio v25.

I see you mentioned here there might be some issues with OBS v25 but I couldn't figure out if you meant to say it shouldn't work.
>Depending on when the last release was made - I believe OBS v25 did do an breaking API change for plugins so they had to be recompiled. And then again - compiled with v25 do not work with v24 and vice versa.. Not sure if v26 will do the same.. so I guess I will hold of a bit longer doing a release.

_Originally posted by @fzwoch in https://github.com/fzwoch/obs-gstreamer/issues/35#issuecomment-694698873_

**Comment by fzwoch** [comment]
The CI build should be fine. I haven't tested myself though. However if its faulty it is most likely to crash and not just not show up.

Make sure you have installed the mingw release of GStreamer and added the "bin" dir with relevant DLLs to the PATH variable of Windows.

**Comment by AvrumFeldman** [comment]
> mingw release of GStreamer 

This was it. I had downloaded the msvc version.

It would maybe be a good idea to mention on the readme that the mingw version is required. (also not to use the dev edition).

Thanks for the quick response.

**Comment by fzwoch** [comment]
Its true. When written there was no MSVC release. The dev package requires the runtime - I hope GStreamer project documents that..
