### ISSUE TITLE
audio only source doesn't work properly

### ISSUE THREAD

**Issue by ethaniel** [fzwoch/obs-gstreamer#38]
Hello,

I am trying to import remote audio into obs via gstreamer - I can see the audio meter fluctuating, but there is no audio on the broadcasted stream.

Audio server:
`gst-launch-1.0 -v alsasrc device=plughw:1,0 ! audio/x-raw,rate=48000,channels=1 ! vorbisenc ! oggmux ! tcpserversink  port=55555`

Client (testing that it works, I can hear the sound):
`gst-launch-1.0 -v tcpclientsrc port=55555 ! oggdemux ! vorbisdec ! autoaudiosink`

OBS client (meter fluctuating, but no audio on the broadcast):
`tcpclientsrc port=55555 ! oggdemux ! vorbisdec ! audio.`

**Comment by fzwoch** [comment]
You can try to tick the "use timestamp" option. Timestamps really are very roughly handled as the OBS documentation on them seem very limited.

**Comment by ethaniel** [comment]
Yep, ticking `use pipeline time stamps` helped!

**Comment by fzwoch** [comment]
Previous commit should improve the situation a bit at least. Re-open in case something pops up again or it breaks other behavior.
