### ISSUE TITLE
aravis gst doesn't works

### ISSUE THREAD

**Issue by rhaamo** [fzwoch/obs-gstreamer#39]
I'm trying to use a source from the gst plugin of https://github.com/AravisProject/aravis but all I get is a grey picture in the plugin.

I'm using `aravissrc camera-name='Aravis-Fake-GV01' exposure=32000 gain=15 ! video/x-raw,width=1028,height=772 ! videoconvert ! video.` as a pipeline.

Using `gst-launch-1.0 aravissrc camera-name='Aravis-Fake-GV01' exposure=32000 gain=15 ! video/x-raw,width=1028,height=772 ! videoconvert ! ximagesink` I do get the test video.

Any ideas what could be wrong ? I've tried running obs with `obs --verbose` but no error is showing.

EDIT: using obs 26.0.2 on linux and obs-gstreamer latest git manually built

**Comment by fzwoch** [comment]
You can run `GST_DEBUG=3 obs` and see some GStreamer related messages in the terminal then.

Note that if you see an image it is kinda already working. At least data seems running through the pipeline. Why it is gray though needs to be checked - could be that `aravissrc` is already sending gray images only.

Try to get an idea whether if it is really only gray frames, or only sending one gray frame and then stops. Perhaps toggling some of the sync/timestamps options change the behavior. Maybe some timestamps are corrupt.

**Comment by rhaamo** [comment]
oops didn't thought about using `GST_DEBUG` with obs !

indeed there is an error:
```
aravissrc gstaravis.c:403:gst_aravis_init_error:<aravis2> error: Could not find camera "'Aravis-Fake-GV01'": Device ''Aravis-Fake-GV01'' not found
```

Changed `camera-name='Aravis-Fake-GV01'` to `camera-name="Aravis-Fake-GV01"` fixed it.

**Comment by fzwoch** [comment]
Thanks for posting the solution. I guess there is something wrong with the string escape parsing with single quotes.
