### ISSUE TITLE
Install is wrong path for Ubuntu / LinuxMint

### ISSUE THREAD

**Issue by crossan007** [fzwoch/obs-gstreamer#4]
```
sudo ninja -C build install
```
dumps the resulting `gstreamer.so` file at `/usr/local/lib/obs-plugins/gstreamer.so` on LinuxMint (Ubuntu).

OBS installed from `apt-get` does not look here for plugins; rather, it looks in `/usr/lib/obs-plugins`

Temp workaround: 
`sudo mv /usr/local/lib/obs-plugins/gstreamer.so /usr/lib/obs-plugins`

**Comment by fzwoch** [comment]
Yeah I guess this is not universal. It probably only covers Linux at all - and then it assumes you have build OBS by yourself too which install itself into `/usr/local`. However I think there is some kind of prefix option when invoking meson where you have some control over it?
