### ISSUE TITLE
Distorted (pitched up) audio

### ISSUE THREAD

**Issue by gdhgdhgdh** [fzwoch/obs-gstreamer#40]
Hello!

Thank you for this great addon for OBS - I am using the gst source to read a remote RTMP stream. The video is very reliable (1 second latency and it recovers gracefully from wifi problem - I am very impressed), but the audio is distorted as if it's been pitched up.

The pipeline is a copy-paste from the project's homepage:

```
uridecodebin uri=rtmp://my.source.ip/faraway/xxxxxxxxxxx06803e64a2dd915844c7b73020714a name=bin ! queue ! video. bin. ! queue ! audio.
```

As mentioned, the audio sounds like it's been shoved up by about an octave - happy to share the URL if we can co-ordinate some testing time :+1: 

Cheers,
Gavin

**Comment by fzwoch** [comment]
That sounds interesting..

That platform and versions are being used?
Can you make a record as an example?
Does the same happen when running from a terminal using `gst-launch-1.0` too?

For the latter running it with `GST_DEBUG=4` may reveal some info about the audio format being used.

**Comment by gdhgdhgdh** [comment]
Sure thing. It's Ubuntu 20.04 in each tested case (my laptop and a server) so gst 1.16.

Gst pipelines drive me nuts. Happy to try with gst launch if you could help with a suitable pipeline. Will try to get a recording later this morning. Cheers!

**Comment by fzwoch** [comment]
From your example above it should be something like this, I hope:
```
gst-launch-1.0 uridecodebin uri=rtmp://my.source.ip/faraway/xxxxxxxxxxx06803e64a2dd915844c7b73020714a name=bin ! queue ! 
videoconvert ! autovideosink bin. ! queue ! audioconvert ! autoaudiosink
```
