### ISSUE TITLE
Win10 pro 64 20H2 + Obs 26.1 64 + gstreamer 18.2 + webcam rtsp do not work

### ISSUE THREAD

**Issue by Engidea** [fzwoch/obs-gstreamer#43]
I can show the camera stream in various ways but NOT in OBS studio

Can play the following from powershell
gst-launch-1.0.exe uridecodebin uri=rtsp://admin:CamPass1212@192.168.1.141/Streaming/channels/101 ! autovideosink

This works in OBS
uridecodebin uri=rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov name=bin ! queue ! video. bin. ! queue ! audio.

This also works in OBS
videotestsrc is-live=true ! video/x-raw, framerate=30/1, width=960, height=540 ! video. 

This does not show anything in OBS
uridecodebin uri=rtsp://admin:CamPass1212@192.168.1.141/Streaming/channels/101 name=bin ! queue ! video. bin. ! queue ! audio.

Nor this
uridecodebin uri=rtsp://admin:CamPass1212@192.168.1.141/Streaming/channels/101 ! video.

Installed gstreamer gstreamer-1.0-mingw-x86_64-1.18.2.msi
Installed OBS OBS-Studio-26.1-Full-Installer-x64.exe

Copied the obs-gstreamer.dll (size=125.591bytes) into C:\Program Files\obs-studio\obs-plugins\64bit

------------------------ further tests done, working

gst-play-1.0.exe rtsp://admin:CamPass1212@192.168.1.141:554/Streaming/channels/101
gst-launch-1.0.exe rtspsrc location=rtsp://admin:CamPass1212@192.168.1.141:554/Streaming/channels/101 !  decodebin ! autovideosink
gst-launch-1.0.exe uridecodebin uri=rtsp://admin:CamPass1212@192.168.1.141/Streaming/channels/101 ! autovideosink

[2020-12-21 16-57-07.txt](https://github.com/fzwoch/obs-gstreamer/files/5725465/2020-12-21.16-57-07.txt)

**Comment by Engidea** [comment]
It is working now, with the following uri

uridecodebin uri=rtsp://admin:CamPass1212@192.168.1.141/Streaming/channels/101 name=bin ! queue ! video.

Also, to lower the latency you MUST uncheck "Sync appsync to clock (video)"

Unfortunately I cannot find out what actually made it work, it would be nice to have some hints of what is not working when nothing is shown. 

In any case, when it is working, it is perfect, what should be, great !!!

Thanks for your work, hopefully you will be repayed in some way

**Comment by fzwoch** [comment]
Oh, missed that post somehow. Always hard to say whats wrong if there is no way to reproduce the problem locally. GStreamer can be very complex, so its hard to print one an exact error. For tracking down such problems I always recommend to export `GST_DEBUG=3` on the console (or a higher number if required/desired) and start OBS (not sure what the easiest way to do that on windows though) and watch the console's output.

Sync appsink clock usually increases latency, therfore it is an option. Some uses cases may work better with it enabled though. Varies on use case.
