### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by marcnnn** [fzwoch/obs-gstreamer#45]
Hey

I am running OBS GIT master version on Arch Linux.

I want to use the filter to split audio to jack from a Browser source.

The filter is first of all only displayed in the  Audio Filters, not in Effect Filters
(I only want to use audio so I would not mind)
In the code, it looks like the filter should be used with video?

when I add the Filter it's not appeared in the list like other filters.

in the std it prints :

info: User added filter 'GStreamer Filter' (gstreamer-filter) to source 'Browser'

and no pipeline Input field is visible.

How can I debug that?

Best
Marc

**Comment by fzwoch** [comment]
I tested with video only. I actually don't know what I would distinguish the two use cases yet. I was looking for makinf something with audio and that lucky worked.

I remember when I started developing this feature I encountered the same that it was supposedly added but never showed up. Maybe it was an audio only source? I thought I fixed it as it is now working fine for me..

Use GST_DEBUG variable to potentially get some more info on the STDOUT on what may be wrong. Else ultimately debugging with a debugger in OBS.

I may have a look if you can explain i details how to reprodice the steps being made.

**Comment by fzwoch** [comment]
Should be addressed by 99c30f30660f9c9f611d66754925cdc6767d5bb8. That is tag v0.3.0. Note that it is still experimental and not well tested. So there may be more things to discover along the way. But some basic echo example is working.
