### ISSUE TITLE
Version details missing from Windows builds

### ISSUE THREAD

**Issue by MikeFarrington** [fzwoch/obs-gstreamer#46]
I was looking at the tagged release notes to see if any recent releases addressed issues I am having, but I could not figure out what version I am currently running.  It would be great if some identifying details could be added to the DLL.  Version information if possible would be ideal, but commit hash in the description field is also useful if obtaining the version number is tricky (unknown at time of build).

![image](https://user-images.githubusercontent.com/40607634/106360250-70892100-62e5-11eb-9f86-d5178d7c36ec.png)

**Comment by fzwoch** [comment]
Not gonna touch these resources to be honest, seems like quite some effort I don't like to maintain. But instead upon module load it prints the git hash it was build from. I hope thats some compromise.
