### ISSUE TITLE
OBS crashes when changing properties while receiving SRT stream

### ISSUE THREAD

**Issue by justincp** [fzwoch/obs-gstreamer#49]
[2021-02-07 14-09-36.txt](https://github.com/fzwoch/obs-gstreamer/files/5940139/2021-02-07.14-09-36.txt)
[crash log.txt](https://github.com/fzwoch/obs-gstreamer/files/5940140/crash.log.txt)

I setup a simple pipeline with the gstreamer plug in:
srtserversrc uri="srt://192.168.100.29:9711?mode=listener" ! decodebin name=bin ! queue ! video. bin. ! queue ! audio.

I am using the Larix app as the client for the SRT stream. If the stream is actively sent, and the user opens the gstreamer source properties page, and clicks OK, then OBS will crash. If the stream is stopped from the app on a separate device, then OBS will update the properties just fine.

**Comment by fzwoch** [comment]
Does that happen reproducible? And only when using SRT? Did you try with something else? Unfortunately that crash log looks very weird. I does not even give a proper module where the crash happens, so I'm not sure if its this plugin making it crash, but if I would have no idea why.

**Comment by justincp** [comment]
It happens every time for SRT but only for SRT. I can change properties just fine for RTSP pipelines.

**Comment by fzwoch** [comment]
Tested on Linux.

On the same host generating a SRT stream
```
gst-launch-1.0 videotestsrc is-live=true ! x264enc tune=zerolatency ! \
    mpegtsmux ! srtsink uri=srt://:8888/ audiotestsrc wave=ticks is-live=true ! \
    voaacenc ! aacparse ! mpegtsmux0.
```

Receiving on OBS side
```
srtsrc uri=srt://127.0.0.1:8888 ! decodebin name=bin ! queue ! video. bin. ! queue ! audio.
```

Seems to be working just fine. Could not make OBS crash when ticking and un-ticking boxes or changing the port number. The client stream was running the entire time playing around with it.
