### ISSUE TITLE
[MacOs] Unable to add gstreamer source

### ISSUE THREAD

**Issue by tinnyx** [fzwoch/obs-gstreamer#53]
Hi,

I've been trying to get this to work yesterday, but didn't manage to. Anything I try leads to not seeing the `gstreamer source` in OBS.

I've tried using default MacOs gstreamer installer, which installs version 1.18.4, and I also added `/Library/Frameworks/GStreamer.framework/Versions/Current` to my `PATH` to see if it would help.

I also tried installing gstreamer through Homebrew, verifying that `/usr/local/sbin` is added to my PATH. This also installs gstreamer version 1.18.4.

Lastly, I tried installing gstreamer through Macports as that's what you mention specifically. I installed the port `gstreamer1`, which installs version 1.16.2, verifying that both `/opt/local/bin` and /opt/local/sbin` are a part of my PATH.

With every approach, I added the MacOs .so variant of `obs-gstreamer` version 0.3.1 to `/Applications/OBS.app/Contents/PlugIns`, but after starting OBS, the `gstreamer source` wasn't in the menu and I didn't manage to find any logs which could lead me to understand what's wrong.

Am I doing something wrong, or do you have any suggestions on what else I could try? I'm running MacOs version 11.2.3.

Thanks!

**Comment by fzwoch** [comment]
Run `otool -L` on the plugin. Check that all file references starting with `/opt` are present on your file system.

**Comment by tinnyx** [comment]
Thanks, using `otool -L`, I was able to figure it out. The plugin looks for the libs in `/opt/local/lib` (as that's where Macports probably installs them, considering it puts the ports themselves in `/opt/local/bin`), but usually on MacOs, libs are located in `/usr/local/lib` (at least from what a quick search suggests https://stackoverflow.com/a/52578857/5177686 ). For now, I just created a symlink `/opt/local/lib` pointing to `/usr/local/lib` and that seems to make the plugin show up in OBS. Thank you!

**Comment by fzwoch** [comment]
Fair enough. The plugin is build via cross compile tool chain. So I guess the port variant there selects a different location than it would be on native macOS. Maybe at some point I will look into `install_name_tool` rewriting these paths to something closer to reality.

**Comment by fzwoch** [comment]
> if you are using macOS, you should install MacPorts using the macOS package installer unless you do not wish to install it to /opt/local/, the default MacPorts location, or if you wish to install a pre-release version of MacPorts base.

Taken from https://guide.macports.org/#installing.macports

So since the pre-built uses Macports I will also leave it as that. Using other install sources may require linking to these specific SDKs in the first place.
