### ISSUE TITLE
Render delay incompatibility

### ISSUE THREAD

**Issue by normen** [fzwoch/obs-gstreamer#54]
Hi,

first of all thanks for this plugin, it makes OBS incredibly powerful, great work!

I seem to have found a bug however that I can reproduce each time. When using a render delay filter to delay the stream theres a cutoff when switching scenes. It looks like the old render delay buffer is being played for some reason.

To reproduce:
- Add a changing gstreamer source to a scene (best use a live input)
- Add a render delay to the source (use the max 500ms, best add two for maximized effect)
- Add another scene with something else playing
- Switch from Scene 2 to Scene 1
- See the last played delay buffer play before a cut to the current delayed video is shown

Thanks again for this software!
Cheers,
Normen

**Comment by fzwoch** [comment]
That may depend on your other settings as well, like whether if you sync to clocks or use timestamps as well. Always depends on the situation. But actually not sure what exactly happens. If scene switching shows something unexpected it may be a bug in OBS itself? This plugin is not buffer anything by itself.. it just delivers data with timestamps..

**Comment by normen** [comment]
> That may depend on your other settings as well, like whether if you sync to clocks or use timestamps as well. Always depends on the situation. But actually not sure what exactly happens. If scene switching shows something unexpected it may be a bug in OBS itself? This plugin is not buffer anything by itself.. it just delivers data with timestamps..

Yeah its strange - I am displaying RTSP based video streams as well as mjpeg based streams from a USB connected camera. I have the plugin set to "use source time" but do not sync it to the main clock - actually I don't 100% get whats being synced with the latter option. However both settings yielded the same result.

Anyway you might be right and this is probably a bug in OBS that for some reason or another shows quicker with this plugin.

**Comment by normen** [comment]
I have experienced this independently of this plugin. I am assuming this has nothing to do with this fantastic plugin, thanks again for making it and sorry for the noise.
