### ISSUE TITLE
Does this even work on Video/Audio?

### ISSUE THREAD

**Issue by alkaris2** [fzwoch/obs-gstreamer#55]
I'm not sure if this plugin for OBS even works properly, no matter what GStreamer filter I try, nothing seems to work. The only one that seems to work by default is this;

```
videoflip video-direction=horiz
```

which just flips the video. But if I wanted to use something like this;

```
videobalance saturation=0.0 ! video/x-raw, framerate=30/1, width=960, height=540 ! videoconvert ! video.
```

it doesn't do anything at all for the video. What it is supposed to do is turn the color saturation down to 0, applying as a filter to an existing source video should be able to take on this effect when applied. If I just create a new source, not applied as a filter, I get the expected result of no saturation but with a test video source if I included `videotestsrc`.

**Comment by fzwoch** [comment]
I'm not quite sure what you are doing. You didn't describe it well to me.

Assuming you want to use the audi/video filter feature, just doing `videobalance saturation=0` does work for me. Note that for the filters you dont need to define a `.video` etc endpoint

**Comment by fzwoch** [comment]
Closing due to no feedback.

**Comment by fzwoch** [comment]
I think you need to dig a little deep where it fails exaclty. Maube `GST_DEBUG=3` helps here. All I can say is that it works for me. The default pipeline as well as your saturation one.

**Comment by kotwys** [comment]
Thank you!

That turned out to be a peculiar issue. It happens only on sources whose resolution is a multiple of 854x480. Here's what gets to the output:

```
0:04:41.864943512 48122 0x7f454c001aa0 ERROR default video-frame.c:181:gst_video_frame_map_id: invalid buffer size 614880 < 616320
0:04:41.864970693 48122 0x7f454c001aa0 WARN  videofilter gstvideofilter.c:296:gst_video_filter_transform:<videoflip4> warning: invalid video buffer received
```

If e.g. `videoflip` is in the pipeline of a GStreamer source producing the exact same video, everything works good there.

```gstreamer
filesrc location=file.mp4 ! decodebin3 name=dec dec.video_0 ! videoflip direction=horiz ! videoconvert ! video.
```

**Comment by fzwoch** [comment]
Sounds like a very specific color format? For `854x480` I would not know what format whould produce 614880 or 616320 bytes of data. May still be a bug in the plugin though..
