### ISSUE TITLE
Installation via Flatpak

### ISSUE THREAD

**Issue by PanderMusubi** [fzwoch/obs-gstreamer#56]
Please offer installation via Flatpak so it can be installed when latest OBS is installed via Flatpak. ( See also https://github.com/WarmUpTill/SceneSwitcher/issues/176 )

**Comment by fzwoch** [comment]
I know nothing about Flatpak tbh. And I think that is not going to change anytime soon. I try to focus on the plugin code. Several different ways of deployment are beyond the scope of this project atm.

**Comment by PanderMusubi** [comment]
Understand. Perhaps one of the users/contributors could work on it.

**Comment by marvin0815** [comment]
Plugin published on Flathub under `com.obsproject.Studio.Plugin.Gstreamer`.

**Comment by fzwoch** [comment]
Nice, thanks! :+1:

**Comment by PanderMusubi** [comment]
Please add to the README that it is possible to install via

    flatpak install com.obsproject.Studio.Plugin.Gstreamer
    flatpak install com.obsproject.Studio.Plugin.GstreamerVaapi

**Comment by fzwoch** [comment]
Done for in their repositories respectively.
