### ISSUE TITLE
Documentation installing release

### ISSUE THREAD

**Issue by PanderMusubi** [fzwoch/obs-gstreamer#57]
Please add to the README.md documentation on how to install this plugin from the obs-gstreamer.zip release file. Here are some paths that could be used for the installation instruction https://github.com/WarmUpTill/SceneSwitcher/blob/master/CI/release/README.txt#L21

**Comment by fzwoch** [comment]
I really don't want to have this kind of documentation in this project. It will just get out of date over time and I really don't want to maintain that (It is very similar to build instructions - which have been broken many times already so I tend to remove them and let the code describe it itself and people have to freestyle from that). Instead I'd rather link to some "official" documentation in the OBS Wiki. Unfortunately I haven't really found such a thing yet, so perhaps someone steps up and creates this page. There are just so many platforms (Linux/macOS/Windows, x86_64/aarch64) and ways to install OBS which has an impact on plugin locations..

**Comment by PanderMusubi** [comment]
If possible, please leave build instructions in until they have found a better home. I know of users of OBS and gstreamer for which building obs-gstreamer is beyond their skills set. There is a need for a pre-build plugin with easy installation instructions (as is found in the scene switcher plugin). Either here or in the OBS wiki.

**Comment by fzwoch** [comment]
Readme has a small hint for Linux plugins now. Hopefully OBS will have better guidance in their docs in the future.
