### ISSUE TITLE
OBS 26.1 crashes after receiving SRT stream as listener after 5h40m

### ISSUE THREAD

**Issue by NemuiBanila** [fzwoch/obs-gstreamer#58]
Hello,

I have a scene with a single gstreamer source: `srtsrc poll-timeout=2000 latency=1500 uri=srt://0.0.0.0:3979?mode=listener ! decodebin name=bin ! queue ! video. bin. ! queue ! audio.`

It is receiving a 3000kbps HEVC stream using MPEG-TS. The sender is connected over a mobile network and sends SRT in caller mode. The video itself works perfectly and the delay is under 1 second.

I am using OBS 64bit on Windows running in admin-mode.

[crash_log.txt](https://github.com/fzwoch/obs-gstreamer/files/6521001/crash_log.txt)

Crash log mentions bmalloc and an OS breakpoint, so this is probably a leak issue. When I was testing another time I saw memory consumption increasing about 1-2MB/s. Using gst-launch there is no increasing memory use.

Gstreamer version: 1.18.4 mingw 64bit
libsrt version: 1.4.3

Thank you

Edit:
I can reproduce this quickly by using:
gst-launch-1.0 videotestsrc is-live=true pattern=snow ! x264enc tune=zerolatency bitrate=50000 ! mpegtsmux ! srtsink uri=srt://127.0.0.1:3979?mode=caller audiotestsrc wave=ticks is-live=true ! voaacenc ! aacparse ! mpegtsmux0.

**Comment by fzwoch** [comment]
That `bitrate=50000` makes it stall for me quite quickly. Even with just `gst-launch-1.0`.

Reducing it to 5000
```
gst-launch-1.0 videotestsrc is-live=true pattern=snow ! x264enc tune=zerolatency bitrate=5000 ! mpegtsmux ! srtsink uri=srt://127.0.0.1:3979?mode=caller audiotestsrc wave=ticks is-live=true ! voaacenc ! aacparse ! mpegtsmux0.
```

And using 
```
srtsrc poll-timeout=2000 latency=1500 uri=srt://0.0.0.0:3979?mode=listener ! decodebin name=bin ! queue ! video. bin. ! queue ! audio.
```
in the OBS plugin runs fine for me.

Tested on Linux:
```
info: obs-gstreamer build: c7729bf

Package: libsrt1.4-gnutls
Version: 1.4.2-1.3

info: OBS 27.0.0-rc4-22-ga05b6f728-modified (linux)
```

**Comment by NemuiBanila** [comment]
I will try testing it on Linux as well.

**Comment by NemuiBanila** [comment]
Using 
```
Ubuntu 20.04.2 LTS

obs-gstreamer - c7729bf
OBS Studio - 26.1.1 (linux)
libsrt1.4.3 - 291e010
gstreamer1.19.0-git - 23f4266
```
the problem does not occur.

Seems to be some kind of Windows-specific leak issue when using the precompiled binaries. My workflow works well with Linux as well, so I will be using obs-gstreamer like this instead.

Documenting this just in case:

The binaries installed on windows were:
https://gstreamer.freedesktop.org/data/pkg/windows/1.18.4/mingw/gstreamer-1.0-mingw-x86_64-1.18.4.msi
https://github.com/Haivision/srt/releases/download/v1.4.3/libsrt-1.4.3-win-installer.zip
https://github.com/fzwoch/obs-gstreamer/releases/download/v0.3.1/obs-gstreamer.zip

All of them were added to PATH

and OBS:
https://github.com/obsproject/obs-studio/releases/download/26.1.1/OBS-Studio-26.1.1-Full-Installer-x64.exe

- The memory increase is happening while the gst-source ```srtsrc poll-timeout=2000 latency=1500 uri=srt://0.0.0.0:3979?mode=listener ! decodebin name=bin ! queue ! video. bin. ! queue ! audio.``` was receiving. 
- OBS is neither streaming nor recording, just previewing. 
- The memory increase is proportional to the bitrate of the received stream. 
- If you change any properties while the source was receiving it would crash as well (and only if the listener was receiving) (see Issue #49 )

**Comment by fzwoch** [comment]
Thanks for checking this out. It is too bad we cannot pinpoint the exact cause.

Do you require the standalone libsrt installer on Windows? I would think that GStreamer installer ships its own srt library. Perhaps the standalone library gets picked instead of the GStreamer's one and cause some issues?

In #49 I cannot remember to have installed anything extra. And I guess since I was investigating crashing when changing properties while it was running I assume I had a configuration quickly set up that was working.

**Comment by NemuiBanila** [comment]
You are right! Gstreamer 1.18.4 ships with a version of libsrt from October 2020. I dug through the strings in the dll a bit and I found its version 1.4.1.

**Comment by fzwoch** [comment]
Closing for now.. if this is still present or we have more insight on the issue please feel free to re-open.
