### ISSUE TITLE
is obs-gstreamer blocking obs?

### ISSUE THREAD

**Issue by ethaniel** [fzwoch/obs-gstreamer#59]
When there is a faulty audio source (`tcpclientsrc host=aaaaaa.ath.cx port=55555 timeout=5 ! watchdog timeout=5000 ! oggdemux ! vorbisdec ! audio.`) where the sending gstreamer audio server is offline, whole obs starts to lag heavily.

Is obs-gstreamer blocking it while trying to establish a connection with the server?

**Comment by fzwoch** [comment]
The state change from NULL to READY in GStreamer is done synchronously. I think that resources are being opened at that stage. So yes GStreamer may block here in case the server is not availabe.

In the plugin it is done in a separate thread, but is synchronized to the start call.

You can try to remove the wait here:
https://github.com/fzwoch/obs-gstreamer/blob/c7729bf494293c3e765dcd286dbbb738c2fec262/gstreamer-source.c#L415

But I guess that can introduce race conditions. That is not easy to avoid.

**Comment by fzwoch** [comment]
Maybe note to myself.

Perhaps moving `create_pipeline()` into `loop_startup()` helps for these situations.

**Comment by fzwoch** [comment]
aed0f187334d2ae157378fa398cf5880e0b73a5d may have improved on the issue.

**Comment by ethaniel** [comment]
Yep, all good now.
Thank you, Florian!
