### ISSUE TITLE
 61ac153 prevents other plugins from modifying pipeline text

### ISSUE THREAD

**Issue by crossan007** [fzwoch/obs-gstreamer#6]
61ac153 introduces a bug(?) where pipeline text modified by another plugin does not execute.

Specifically, I'm seeing it here: https://github.com/crossan007/obs-gstreamer-device-mapper/blob/master/lib/NetCamClientHandler.py#L62

After the pipeline is updated via `obs.obs_source_update(source, settings)`, the TCP port expected to be opened by gstreamer pipeline `tcpserversrc host=0.0.0.0 port={port} ` is never opened.

This could also be a bug in the way I'm telling obs-gstreamer about new pipeline text.

**Comment by crossan007** [comment]
I think it's actually the null check for `data->pipe` on https://github.com/fzwoch/obs-gstreamer/blob/master/gstreamer.c#L386

If I remove that if statement, then it works as I desire.    

I'm still a bit fuzzy on dereferencing pointers, but I believe this null check would prevent new `data->pipe` from ever being created when a new pipeline text is supplied via `static void update(void* data, obs_data_t* settings)`?

**Comment by fzwoch** [comment]
I'm actually unsure about the expectations here. So now when you update the pipeline string it will also start the pipeline - even when the source is actually hidden. Is that intended?

I mean. If it is hidden I would expect you update the string, then I would also expect you to unhide the source to make the changes take effect.

So maybe it was correct in the first place where updating the pipeline string would not automatically start the pipeline?

**Comment by crossan007** [comment]
Maybe I'm over-interpreting the setting, but if "stop_on_hide" is unchecked, then I expect that source will always be either "PLAYING" or trying to play.  Maybe the setting or alt text should be: "always play source, even when not visible."

That said, my plugin responds to external stimuli - whenever a remote device is discovered, the GStreamer pipeline is automatically negotiated and executed, so I would prefer that text updates to the pipeline are executed, even if the source is not visible.

**Comment by crossan007** [comment]
I'd like to avoid any delay in waiting for the pipeline to start when switching to a previously hidden source.

**Comment by crossan007** [comment]
It hadn't occurred to me that I could invoke obs-gstreamer `start ()` from my plugin.  That would probably do the trick.

Ill try it out later today.

**Comment by crossan007** [comment]
resolved by 58315bd429df6c269b487e022f11130719367e92
