### ISSUE TITLE
preprocess filter pipeline to add filename or current date-time

### ISSUE THREAD

**Issue by belonesox** [fzwoch/obs-gstreamer#61]
I wish translate and record source signal, using GST pipeline like this:

```
videotestsrc is-live=true ! tee name=srctee ! queue ! filesink location=/home/stas/test.dv async=0 srctee. ! decodebin ! videoconvert ! videoscale !  video.
```

BTW, this pipeline works. 

But of course, I dont want to hardcode paths, and want to generate filename using common 
OBS format for filenames, like 
"somesource-%CCYY-%MM-%DD-%hh-%mm-%ss"

(because I dont want to override recorded file every recording).

and PATH to recording can be taken from OBS settings.

So I want something like this 

```
videotestsrc is-live=true ! tee name=srctee ! queue ! filesink location=%OBSPATH-sourcename-%CCYY-%MM-%DD-%hh-%mm-%ss.myext async=0 srctee. ! decodebin ! videoconvert ! videoscale !  video.
```
but something simpler, like 
```
videotestsrc is-live=true ! tee name=srctee ! queue ! filesink location=%OBSPATH-sourcename-%ISOTIMEWITHDASHES.myext async=0 srctee. ! decodebin ! videoconvert ! videoscale !  video.
```
should also be OK.

**Comment by fzwoch** [comment]
The pipeline string is just a string. As workaround consider setting the pipeline property via a script that sets this string with better timestamping. Nothing I consider implementing in the plugin itself.

**Comment by belonesox** [comment]
I will be waiting for it.

In fact, I've been waiting almost three years for this, and there is a workaround
https://github.com/exeldro/obs-source-record

But recording original sources using «filesink» of course will be better.
