### ISSUE TITLE
«gst_uri_handler_get_uri: assertion 'gst_uri_is_valid (ret)' failed» → «double free or corruption (out)» 

### ISSUE THREAD

**Issue by belonesox** [fzwoch/obs-gstreamer#62]
I am experimenting with «hdv1394src» pipelines.
Now got situation, that obs-gstreamer with filter
```
hdv1394src ! tee name=srctee ! queue ! filesink location=/home/stas/test.dv async=0 srctee. ! decodebin ! videoconvert ! videoscale !  video.
```
worked, until I tried to make something with the source (stop preview, or start editing pipeline) 
then OBS crashed. 

like this  https://vimeo.com/99375769

Log:  https://gist.github.com/belonesox/2a322b67fe763121f839aea82a3e13e2

Is there some VERBOSE_DEBUG mode to explore?

```
obs-gstreamer: 9ed970d04e0d231e8ac4acef595117e5067a6de5
obs-studio-libs-27.0.1-1.fc33.x86_64
obs-studio-devel-27.0.1-1.fc33.x86_64
obs-studio-27.0.1-1.fc33.x86_64
```

**Comment by fzwoch** [comment]
You can start OBS with `GST_DEBUG=3 obs` for getting more detailed GStreamer info. However this seems to be a hard crash, so `gdb --args obs` should give tou a stack trace once it crashes. However if the crash happens inside GStreamer there is not much this plugin can do. But check where this double free is actually happening.

**Comment by belonesox** [comment]
I already start «GST_DEBUG=3 obs», check gist from first comment https://gist.github.com/belonesox/2a322b67fe763121f839aea82a3e13e2

**Comment by fzwoch** [comment]
Assuming this is something with GStreamer and hdv1394src closing this here.
