### ISSUE TITLE
gstreamer encoder not respecting bitrate setting

### ISSUE THREAD

**Issue by ethaniel** [fzwoch/obs-gstreamer#67]
Hello!
Once again, thank you for the amazing plugin. 

I just tried streaming HEVC via HLS to Youtube by using the "Gstreamer Encoder" option in the encoder settings. The bitrate is set to 6000 kbps, however I can see the actual traffic being 100000 kbps (confirmed by iptraf-ng).

<img width="281" alt="Screen Shot 2021-12-14 at 14 45 18" src="https://user-images.githubusercontent.com/941973/145954729-90bae4a6-7bd2-4d59-b691-acafc6c8287b.png">
<img width="749" alt="Screen Shot 2021-12-14 at 14 45 14" src="https://user-images.githubusercontent.com/941973/145954740-8e3abb68-ce9f-4323-b34f-1554af5890f3.png">

**Comment by fzwoch** [comment]
Did you use a version that includes this change: 219a62963f206ef521eb1b12dddd5b971348128b?

Apart from that, I have never tested the NVENC implementation. It is potentially possible, that that I have mixed up the scale of the bit rate options between OBS and GStreamer's NVENC.

Apart from that, this will be the H.264 encoder. IIRC OBS does not yet expose custom HEVC codec options - or any HEVC options besides using custom FFMPEG which is very relaxed by its design.

So for the use case of NVENC H.264 one should have a very good reason to use the GStreamer encoding over OBS's regular NVENC option.

**Comment by ethaniel** [comment]
Ahh, so there is no way to make gstreamer encode in h265? 

i was under the impression that obs was sending the raw video stream and gstreamer was the one responsible for encoding.

**Comment by fzwoch** [comment]
GStreamer can do HEVC/H.265 just fine. But inside OBS it has to cooperate with OBS and OBS is not yet prepared for HEVC. So that would need to change first.

**Comment by ethaniel** [comment]
Thank you!

**Comment by fzwoch** [comment]
Just out of curiosity. In your test, was the commit applied or not? I just wonder what the state of the NVENC inside GStreamer is. The bitrate settings I use for example are not even found in their documentation.

**Comment by ethaniel** [comment]
My .so was built on November 3. So I guess not, since your commit is of 8 days ago.
