### ISSUE TITLE
Plugin not loading in OBS - Windows

### ISSUE THREAD

**Issue by roxaskeyheart** [fzwoch/obs-gstreamer#68]
Hi there,

I just installed the gstreamer runtime on Windows, and then added the bin folder of the install to PATH, before then adding your plugin to the OBS Studio's plugin directory (x64).

Plugin was added to this directory: C:\Program Files\obs-studio\obs-plugins\64bit\

When looking in the OBS startup log, I can see this also:
`14:09:30.297: LoadLibrary failed for '../../obs-plugins/64bit/obs-gstreamer.dll': The specified module could not be found.`

Any ideas on what might be happening?

**Comment by roxaskeyheart** [comment]
Nevermind, I had the wrong gstreamer package installed.

**Comment by fzwoch** [comment]
MSVC version instead of MinGW I assume?
