### ISSUE TITLE
RTSP stream does not work

### ISSUE THREAD

**Issue by MrAntooo** [fzwoch/obs-gstreamer#69]
Hi, I'm using the plugin with OBS and it works great with Dahua cameras, but with Panasonic's RTSP stream (example link: rtsp://root: root@123.456.789.000: 554/MediaInput/h264) and I can't understand why.

Thank you for your help.

**Comment by fzwoch** [comment]
That sounds like an issue with GStreamer RTSP or the camera. Not an issue with this plugin per se.
