### ISSUE TITLE
Scaling the video in encoder option crashes obs

### ISSUE THREAD

**Issue by RushingAlien** [fzwoch/obs-gstreamer#71]
Hello there!, great work with the plugin. exactly as the title says, when dowscaling option is enabled, it crashes obs.
![gambar](https://user-images.githubusercontent.com/80886145/164751183-e0d5f205-c3d3-48b4-8c38-0d19f405bd79.png)

**Comment by fzwoch** [comment]
Thanks for the report. I think this is fixed with the above commit.

**Comment by RushingAlien** [comment]
Thank you so much, that was _fast_.
You're a legend.
