### ISSUE TITLE
issues with h265

### ISSUE THREAD

**Issue by ethaniel** [fzwoch/obs-gstreamer#72]
Hi!

I've noticed that when I switch the video feed from h264 to h265, I'm getting much more crashes on the obs side.

Here is the pipeline that I'm using:
```
rtspsrc location=rtspt://guest:gstreamer1@45.59.200.85:5540/Streaming/Channels/101 !  rtph265depay ! queue ! avdec_h265 ! queue ! videorate ! video/x-raw,framerate=30/1 ! watchdog timeout=10000 ! queue2 ! video.
```
(feel free to test it, it will give you an actual video feed)

Everything is working fine, but for example, when I save this pipeline again, obs crashes with the "double free or corruption (out)" error in the console. 

When I switch the video feed back to h264 and replace all rtph265depay and avdec_h265 with their h264 counterparts, I don't have this problem anymore.

Thank you.

https://user-images.githubusercontent.com/941973/164942021-af41e40b-23d4-4ec6-ace0-039c9dab2348.mp4

**Comment by fzwoch** [comment]
Assuming the pipeline is correct and the camera support H.265 - did you try running it without OBS and the plugin from the command line?

I would not know what specifically should be different from H.264 to H.265 from a plugin perspective. So I kind of expect the issue to be present in the GStreamer runtime itself. Which version of GStreamer do you have installed?

**Comment by ethaniel** [comment]
After some digging, found out that it was a gstreamer bug after all. It's fixed in the latest versions. 
Thank you and sorry :)

**Comment by rodrigograca31** [comment]
@ethaniel what version fixed it?

how did you install it?
I got the latest of my distribution (OS: Linux Mint 20.3 x86_64) which is supposed to have all bugs fixed but im experiencing the same issue as you... 

```
double free or corruption (out)
[1]    590395 abort (core dumped)  obs
```

if I switch my camera to h264 and switch the gstreamer pipeline to h264 it works but it would be better to use h265 for less bandwidth....

**Comment by rodrigograca31** [comment]
my OS  (Linux Mint) actually just received an update to gstreamer 1.16.3 but doesnt seem fixed yet....

**Comment by fzwoch** [comment]
You could try to use `gdb` for a stack trace so you gen an idea where it may be crashing.

**Comment by fzwoch** [comment]
> my OS (Linux Mint) actually just received an update to gstreamer 1.16.3 but doesnt seem fixed yet....

GStreamer 1.16 was released in 2019. Expect it to have bugs. Current version is 1.20.

**Comment by rodrigograca31** [comment]
> GStreamer 1.16 was released in 2019. Expect it to have bugs. Current version is 1.20.

damn! they are slow! 😭
