### ISSUE TITLE
More codec options in the Encoder

### ISSUE THREAD

**Issue by RushingAlien** [fzwoch/obs-gstreamer#76]
It would be nice to have more codecs to choose from, such as vp8, vp9, hevc or av1. Especially with many newer GPUs starting to support AV1.

**Comment by fzwoch** [comment]
The main problem is that OBS expects H.264 for its downstream functionality (maybe H.265 too by now, not sure) but not arbitrary codecs.

If one really wants to work with others, one could try to use the GStreamer custom output module. It is just not in the GUI and needs to be done programtically.
