### ISSUE TITLE
Build in Linux Mint fails?

### ISSUE THREAD

**Issue by rodrigograca31** [fzwoch/obs-gstreamer#77]
```
OS: Linux Mint 20.3 x86_64 
Kernel: 5.15.0-41-generic 
OBS: 27.2.4
```

I was trying to use this plugin but it crashes my OBS quite a bit... not sure if its related to h265 or if Im doing the pipeline thing wrong because I have no idea what im doing....

I get it playing but when I switch scenes OBS crashes...

because it was crashing a lot I decided to try to compile/build it my self to see if that solved the crashes.
after installing messon and cmake I run `meson --buildtype=release build`and get 
```
Run-time dependency gstreamer-1.0 found: NO (tried pkgconfig and cmake)

meson.build:33:0: ERROR: Dependency "gstreamer-1.0" not found, tried pkgconfig and cmake
```

![image](https://user-images.githubusercontent.com/1134310/181660782-adf1ef20-ed74-438b-94f2-df347aa028b4.png)

**but I do have gstreamer-1.0 installed or I wouldnt be able to play stuff on OBS right? and outside OBS using**
`gst-launch-1.0 -v playbin uri=rtsp://USER:PASS@IP/Streaming/Channels/101 uridecodebin0::source::latency=0`

welp? 
maybe its me not knowing how to "build" the pipeline thing correctly for h265 ... ? 
I think I got it working before with h264 but I would prefer h265....

**Comment by fzwoch** [comment]
1) Check if you GStreamer version is up to date. There have been reported bugs with H.265 before and it seemed to be related to bugs in upstream GStreamer.

2) You will need the developer package of GStreamer to build the plugin. On debian based systems these are packaged usually postfixed with `-dev`. Not sure how it is on Mint.

**Comment by fzwoch** [comment]
For the H.265 specific see #72.

**Comment by fzwoch** [comment]
Closing since not a bug.

**Comment by rodrigograca31** [comment]
after installing the developer package `-dev` it went a few lines forward but then hit:
`Run-time dependency gstreamer-video-1.0 found: NO (tried pkgconfig and cmake)`

so I give up... 
also I tried to measure 1min of h264 bandwith vs 1min of h265 bandwith and it seemed virtually the same.... not sure my measurement technique was correct tho....... so if they are the same I will just switch to h264.

I was using h265 for 8 cameras, I was assuming it was saving me bandwidth in case I wanted more cameras....

**Comment by fzwoch** [comment]
The GStreamer video package is just another developer package of GStreamer. It is split up in several components.

The bitrate being used should be setable in the camera. Both codecs can do the same bandwidth. It is just a different trade off between bandwidth and picture quality.

**Comment by rodrigograca31** [comment]
> The bitrate being used should be setable in the camera. Both codecs can do the same bandwidth. It is just a different trade off between bandwidth and picture quality.

unfortunately seems its not that simple. as you can see in the graph bellow just changing from h265 to h264 made the bandwith almost double from arround 6MB to 10MB during the experiment period (night) and back down after about 14:00  when I switched back to h265.

![image](https://user-images.githubusercontent.com/1134310/183256832-62675d62-c747-46a3-a9d8-2fe1213f3b32.png)

Honestly my network probably can handle it but less traffic is always better/faster and I wonder when I got 20 cameras if it still handles it well. also im switch to obs-gstreamer to make it faster (no 2s delay) so having it use more bandwith could make it slightly slower....

**all this to say that I'd really like to make h265 work without crashing OBS.....**
also theres a new version of OBS in beta (28.x) with huge changes. maybe this will get fixed by then.......

**Comment by fzwoch** [comment]
> also I tried to measure 1min of h264 bandwith vs 1min of h265 bandwith and it seemed virtually the same.

So that was incorrect then?

Anyway, you really have to investigate where it crashes. Without any logs and backtraces nobody can say anything. At leas the module and function is happening needs to be known.

**Comment by rodrigograca31** [comment]
> > also I tried to measure 1min of h264 bandwith vs 1min of h265 bandwith and it seemed virtually the same.
> 
> So that was incorrect then?
> 
good question! I forgot I did that test! but the bigger test with 8 cameras during all night definitely shows a difference. 
(here is the big spike in the middle during Saturday 06 August)
![image](https://user-images.githubusercontent.com/1134310/183292323-c25a5167-2b00-4b9e-92f8-7279f867539a.png)


> Anyway, you really have to investigate where it crashes. Without any logs and backtraces nobody can say anything. At least the module and function it is happening at needs to be known.

yeah I will try. any ideas on how to get more info?
OBS only said:
```
double free or corruption (out)
[1]    590395 abort (core dumped)  obs
```
