### ISSUE TITLE
GStreamer encoder not applying saved bitrate while streaming

### ISSUE THREAD

**Issue by pmartiner** [fzwoch/obs-gstreamer#78]
Hi!

I'm facing an issue with the plugin while streaming. It looks like the encoder is not respecting my bitrate (similar issue as #67). And not only that: the output of my stream looks like is being downgraded to the default bitrate (2500kbps) and to a 720p resolution, even though I have a 6000kbps bitrate at 1080p in my settings. This, however, does not happen when I record the video. I'm using the latest version (v0.3.4) from the AUR. I've also tried the prebuilt plugin, but the problem is still there

Here are some screenshots of the issue:
![stream](https://user-images.githubusercontent.com/25936810/182004102-76a8d30e-7ab4-4195-9634-8116f3aadae8.png)
![kbps](https://user-images.githubusercontent.com/25936810/182004105-4c2669b2-ac2a-4862-8ebd-dd24382fedbf.png)
![settings](https://user-images.githubusercontent.com/25936810/182004107-f126434f-b368-4db8-ad94-71fa52d4edef.png)

Is this a bug? May I help with some logs? Thanks!

**Comment by fzwoch** [comment]
An OBS log always helps. Not sure what should be the differnce between recording and streamign though.

Oddly enough you screenshot says it is streaming at 11mbps. Maybe your streaming provider transcodes the video to low quality?

**Comment by pmartiner** [comment]
Sure thing! [Here are my logs](https://github.com/fzwoch/obs-gstreamer/files/9228105/2022-07-31.00-18-51.txt). I tried to stream and record with the Gstreamer encoder as well as streaming with AMF in case that comparing them may be useful for the debugging process.

Yeah, I would think that if OBS is streaming at 11mbps the output quality would be waaay better. Maybe that's just a Twitch thing.

Weirdly enough, unless I set the type on the Recording tab to "Custom Output (FFmpeg)" and the Video Bitrate manually to 6000kbps, the output looks the same as when streaming. Maybe it has to do with that?

**Comment by pgwipeout** [comment]
Twitch generally enforces a max cap of 6m, you can push it a bit higher, but not by much. They do support auto transcode for non partners on a space available basis. Use twitch inspector to view statistics of your incoming video.

Since "source" isn't an option here I'd venture it's because you're too high above their limits.

**Comment by pmartiner** [comment]
@pgwipeout yeah, I imagine that's the reason it's playing it at 720p. However, even if I set the bitrate to 6mbps on the Gstreamer encoder settings in the Streaming tab, the config is not being respected :/

**Comment by pgwipeout** [comment]
What does twitch inspector say?

**Comment by pmartiner** [comment]
it looks like the bitrate's okay, but there's a compatibility issue: 
![image](https://user-images.githubusercontent.com/25936810/182014102-a1fec65d-e153-4f28-b8fd-4cf5f1118b1f.png)

**Comment by pgwipeout** [comment]
Are you running adaptive bitrate? I recommend you look into twitch's recommended streaming settings.

**Comment by pmartiner** [comment]
@pgwipeout nope. these are my current settings: ![settings](https://user-images.githubusercontent.com/25936810/182004107-f126434f-b368-4db8-ad94-71fa52d4edef.png)

**Comment by pgwipeout** [comment]
The bitrate spike is a problem if it happens regularly, also it's concerning the video and audio encoder aren't being passed through correctly. That's probably a string that this plugin should be setting (just a guess here).

**Comment by pmartiner** [comment]
@pgwipeout I guess that the encoders weren't passed to the inspector because I was running a test stream. Here's a screenshot with a "live" stream: 
![image](https://user-images.githubusercontent.com/25936810/182014688-b4d4d918-ac79-40a0-a7b0-582c43d97c35.png)

**Comment by fzwoch** [comment]
Here is my config and result.

![Screenshot from 2022-07-31 09-16-35](https://user-images.githubusercontent.com/439605/182014690-1bf372ed-85cc-4ce6-bdc9-419773020679.png)
![Screenshot from 2022-07-31 09-15-51](https://user-images.githubusercontent.com/439605/182014691-ed340245-31a0-420f-8e97-0f0f16e51a90.png)

**Comment by pmartiner** [comment]
hmmm, weird. it looks like we have the same settings @fzwoch. maybe it has to do with the distro I'm running (Arch Linux)? 'cause I've tried both the flatpak version and tytan's version of OBS and the issue is still there.

**Comment by pgwipeout** [comment]
Most likely it's your actual hardware encoder here. Some are more stable than others.

With those settings you should be seeing "source" as an option on your live stream. If you're seeing artifacting on the "source" stream that's either your hardware or the driver.

**Comment by pmartiner** [comment]
@pgwipeout yup, those artifacts appear when the "source" option is selected. I find it weird that the encoder's kinda unstable given that the inspector does not complaint about the stabilty. I'm not ruling it out, since I have a low-end RDNA(1) GPU (5500XT), but I just find it weird.

(I tried running OBS with the RADV drivers as well as with the AMDGPU PRO ones and the output's the same. I also suspect that it may have to do with the [FFmpeg version I'm running](https://aur.archlinux.org/packages/ffmpeg-obs))

**Comment by fzwoch** [comment]
My stream looks good for me. I personally use an RX 570 so I doubt it should be an issue with the 5500 XT. I tried with the Ryzen G series in the past too with no problems. At some point I had it running on a 5700 too.

**Comment by pgwipeout** [comment]
Funnily enough, the older radeons are some of the ones that are unstable. It's gotten better with rdna2 but we still have reports of weird behavior on some of them.

**Comment by pmartiner** [comment]
@fzwoch true. I tried with the "regular" FFmpeg and nothing changed :/

@pgwipeout yeah, it may be, especially if no one else has faced this issue

**Comment by fzwoch** [comment]
FFMPEG VAAPI is the same issue?

Then maybe it is your mesa driver version that's causing it.

**Comment by pgwipeout** [comment]
All of the encoder "work" is done by the GPU silicon. There's some minor post processing that can be handled by the CPU, but anything major is expensive(thus you'd notice if you were doing it).

If you want to verify it's a hardware problem, pop the card in a windows machines and verify with those drivers.

**Comment by pmartiner** [comment]
@fzwoch @pgwipeout yup, the same thing happens with FFMPEG VAAPI. Does that confirm that's a Mesa driver issue? I'm currently running v22.1.4

**Comment by pgwipeout** [comment]
Using the encoder directly through the va-api interface won't touch mesa as it's directly calling the kernel encoder api. Mesa only comes into play when video is displayed.
If the stream looks broken on another device, then it isn't a display issue. You should validate your hardware isn't one of the bugged ones.

**Comment by pmartiner** [comment]
@pgwipeout it looks like the hardware's not the issue. it looks great on windows:
![image](https://user-images.githubusercontent.com/25936810/182017525-b908b095-f7d6-4ffa-9b91-4fcef0eb6226.png)
![image](https://user-images.githubusercontent.com/25936810/182017529-82524436-5d89-4a1d-9631-9e7910b4e77b.png)

**Comment by pgwipeout** [comment]
x264 is a cpu encoder. You need an external plugin for amf to work on OBS for windows.

**Comment by pmartiner** [comment]
@pgwipeout I usually stream with AMF on windows as well and the output looks great. Here are some screenshots: 
![image](https://user-images.githubusercontent.com/25936810/182017970-21b74d6f-b1bc-4d5f-a4a2-205cdb783f95.png)
![image](https://user-images.githubusercontent.com/25936810/182017992-89d63ad7-872c-4b09-8ba5-bfad6211bb92.png)
![image](https://user-images.githubusercontent.com/25936810/182018002-7554275f-f835-47a7-8b37-93afc6d03320.png)

**Comment by fzwoch** [comment]
At the end I do not understand why the recording turns out good, while the stream does not. Unless you have different encoders or encoding settings for them.

**Comment by pgwipeout** [comment]
I suspect this is a data rate / data starvation problem. Recording can buffer until an entire frame or group of frames is ready and run them through the encoder, where streaming will run as fast as the pipeline will allow. IIRC the AMD encoder needs this in order to perform well. They stated the AMF plugin for Linux worked well, while pumping through the VA-API directly does not. I suspect the AMF plugin is doing something behind the scenes to mitigate this weakness. I don't spend a lot of time messing with gstreamer pipelines, but is there a way to ask it to buffer a frame or two? Another possibility is we are building the pipeline without B Frames. See this article for info: https://www.tomshardware.com/news/amd-amf-encoder-quality-boost

**Comment by pmartiner** [comment]
I the recording report was an issue on my part :s, my bad!!! I didn't realize that I was indeed using a different encoder. After changing the settings the Gstreamer Encoder, the output looked the same as when streaming. 
(The bad quality video does happen with FFMPEG VAAPI and the Gstreamer Encoder when streaming and recording)

**Comment by fzwoch** [comment]
Ok, I guess I will close it then. Looks like the issue seems to be in the VAAPI layer or driver, but not in this plugin.

**Comment by pmartiner** [comment]
Thank you for the help and for your time!
