### ISSUE TITLE
ICQ and CQP levels

### ISSUE THREAD

**Issue by mesmerx** [fzwoch/obs-gstreamer#82]
i get the ICQ and CQP can be more or less controlled by the bitrate, 

if i set bitrate to 40000 and only need 30000 to keep quality it only uses 30000, or iif i have a black screen it uses liike 700 bitrate
iif i set bitrate to 3000 it uses 3000 or less

but i wanna know if exist another parameter, maybe ICQQuality,  or a thing to configure the level of qualiity, thx :)

**Comment by fzwoch** [comment]
Consider switching to https://github.com/fzwoch/obs-vaapi

That one has a property page for all available options. You will have to do some research or testing what works an how it works for your particular hardware though. I cannot answer that.
