### ISSUE TITLE
Constant QP rate control option in the GStreamer Encoder doesn't work.

### ISSUE THREAD

**Issue by niobium93** [fzwoch/obs-gstreamer#83]
When using the Constant QP rate control option in the GStreamer Encoder settings, there is no option to set the QP, instead the Bitrate control stays in place.
![obs gstreamer encoder settings](https://user-images.githubusercontent.com/1523948/188074889-758f463c-7495-485d-a140-0b92f2d6f2bf.png)

**Comment by niobium93** [comment]
Would also be nice to be able to set the Profile and Level

**Comment by fzwoch** [comment]
Everything you mention can be archived by using the extra encoding options. It is far easy usable, I know, but it will not change.

You may want to look at https://github.com/fzwoch/obs-vaapi where a lot more options are being exposed. It is supposed to be supersede this one for the vaapi encoder functionality.

**Comment by niobium93** [comment]
Thanks, I'll use `obs-vaapi` then.

**Comment by jazztickets** [comment]
Try putting something like `rate-control=cqp init-qp=18 cabac=true` in the extra encoder options box. Running `gst-inspect-1.0 vaapih264enc` shows you all the options.

**Comment by niobium93** [comment]
@jazztickets Thanks, but I'm using [obs-vaapi](https://github.com/fzwoch/obs-vaapi) now.
