### ISSUE TITLE
Can't output Audio to device

### ISSUE THREAD

**Issue by LUBEProductions** [fzwoch/obs-gstreamer#84]
Hello,
I have many sources in OBS, with their separate audio Source in the OBS mixer. And I want to be able to output these sources from OBS to my Mixing board. But because I am on Linux, Plugins like [OBS Audio Monitor](https://obsproject.com/forum/resources/audio-monitor.1186/) don't work for me, because the developers don't care. Then I found this Plugin. The GStreamer Source Plugin works fine, but every time I try and use the "GStreamer Filter (Audio)" Plugin, it gives me the Error: "error: could not link audioconvert184 to appsrc184" many times a second, with the two numbers going higher every time. When I connect two audio points through gst-launch, everything works fine!

I've already tried:
"appsrc ! audio/x-raw,channels=2,rate=48000 ! pipewiresink"
- add queue at different places
- add audioconvert at different places

Am I missing something? Am I doing something wrong?

Thanks for your feedback
(Great Plugin BTW)

**Comment by fzwoch** [comment]
What are trying to do? aoosrc does not make much sense for this plugin as you have no means to control it,,

**Comment by LUBEProductions** [comment]
Oops, I have misspelled pipewiresink. (Updated)
I am trying to route the output of this plugin (added as effect) to pipewire, so I can route it from there to my mixer.
OBS Source ---> OBS Mixer ---> OBS GStreamer ---> PipeWire ---> ALSA ---> My Mixer

**Comment by fzwoch** [comment]
I see, then you need to branch away, like this:

```
tee name=t ! queue ! autoaudiosink t. ! queue
```

Use pipewire instead of the audiosink. Eventually add resampler/converter depending on what pipewire wants to have.

**Comment by LUBEProductions** [comment]
Thanks! It actually works! (although i had to switch up the output to alsasink to prevent [this](https://github.com/fzwoch/obs-gstreamer/files/9539760/untitled.zip) from happening)

But right now the Latency is around one to two whole seconds. Is there a way to decrease that?

**Comment by fzwoch** [comment]
I guess you will need to play around with sync or async options and how latency is determined with a specific pipeline in general. The plugin itself won't add any extra latency by itself.

Guess I'll close this as in general it seems working.

**Comment by LUBEProductions** [comment]
Well still thanks for your Help!

**Comment by LUBEProductions** [comment]
> I guess you will need to play around with sync or async options and how latency is determined with a specific pipeline in general. The plugin itself won't add any extra latency by itself.
> 
> Guess I'll close this as in general it seems working.

I have some really strange behavior now... When I start obs the latency is high, but when I update the pipes like in [this example](https://github.com/fzwoch/obs-gstreamer/files/9539817/untitled.zip) (Clicked Apply at the 11.8 Second Mark) the Latency is super low! Is this a GStreamer or Plugin issue?
