### ISSUE TITLE
How to use intel igpu

### ISSUE THREAD

**Issue by poopman97** [fzwoch/obs-gstreamer#87]
I'm trying to use this with my intel igpu with nvaapi but it doesn't work and it only uses the software encoder.
So can this work with intel gpus or is it only for amd?

**Comment by fzwoch** [comment]
`doesn't work` could be anything.

Maybe you want to check out https://github.com/fzwoch/obs-vaapi
At least do the checklist part from there.

**Comment by poopman97** [comment]
I've done the checklist and the `gst-inspect-1.0 va` commands doesn't work and I don't know what package to install to make the va plugin work

**Comment by fzwoch** [comment]
The va one is only required for the other repository. But will have to check with you Linux distribution on how to install certain things.

**Comment by poopman97** [comment]
I've just tried it without the va plugin and it works perfectly fine so it's probably unessery anyway thanks for the help
