### ISSUE TITLE
No encoder type OBS 29 Beta

### ISSUE THREAD

**Issue by aleksasiriski** [fzwoch/obs-gstreamer#90]
![image](https://user-images.githubusercontent.com/31509435/206137844-601704b8-e015-47d3-9948-80d0aedd173b.png)

No encoder type on Flatpak OBS 29 Beta, even though it shows VAAPI on OBS 28. I have gstreamer-vaapi installed.

![image](https://user-images.githubusercontent.com/31509435/206138265-83a4a16c-3c86-41cf-ada4-88ff88a5afe9.png)

**Comment by fzwoch** [comment]
I have no idea whether flatpak supports the OBS beta. But if no codecs appear it is most likely you don't have installed the GStreamer plugins that have the different encoders in them.

**Comment by aleksasiriski** [comment]
> I have no idea whether flatpak supports the OBS beta. But if no codecs appear it is most likely you don't have installed the GStreamer plugins that have the different encoders in them.

Flathub-beta has OBS 29 Beta 1, codecs are correctly installed (since they work with OBS 28). Is this plugin working correctly for OBS 29?

**Comment by aleksasiriski** [comment]
Maybe gstreamer-vaapi doesn't support 29?

**Comment by fzwoch** [comment]
It does.

**Comment by aleksasiriski** [comment]
OBS logs:
```
VAAPI: API version 1.15 
FFmpeg VAAPI H264 encoding not supported
```

Maybe OBS doesn't support new Mesa (Extra):
https://www.reddit.com/r/Fedora/comments/zekw5j/mesa_2224_flatpak_just_landed_solving_the_patent/
