### ISSUE TITLE
0.4.0 system-wide install from source is broken

### ISSUE THREAD

**Issue by tytan652** [fzwoch/obs-gstreamer#99]
It looks like this commit https://github.com/fzwoch/obs-gstreamer/commit/4ca74407b0e056df5d8d57526bf41dfcb100f333 has broke system-wide install on Linux.

I end up with `/usr/obs-gstreamer.so`

Edit: I had to revert the commit to make the AUR package work again.
Edit: On Linux, plugins install default is system-wide.

**Comment by fzwoch** [comment]
Oh, yeah that is true. I figured majority of people want to install it to their home directory without having to become root or figure out the exact path. (Well, basically me..)

I hope it would be okay to give additional parameters for a system install (as it may be different from system to system in many cases)?

So for example this should work:

```sh
meson setup --prefix=/usr --libdir=lib/obs-plugins
```

Which would install in `/usr/lib/obs-plugins`.

**Comment by tytan652** [comment]
Update the readme, and maybe warn in the changelog/release of such changes in the buildsystem.

**Comment by fzwoch** [comment]
Yeah sorry about that. I always forget about the system integrators.

I have updated the README.

**Comment by marvin0815** [comment]
> I forgot, I don't remember if such thing can be done to the Flatpak.

I found no way tbh and had to revert commit 4ca74407b0e056df5d8d57526bf41dfcb100f333 to get the plugin included or the install path gets ignored oven with libdir set :-/

**Comment by tytan652** [comment]
@marvin0815 maybe try to use:

```yaml
build-options:
  prefix: /app/plugins/Gstreamer
  libdir: lib/obs-plugin  
```
